# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: coda/v1/got.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'coda/v1/got.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from coda.v1 import clinical_pb2 as coda_dot_v1_dot_clinical__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11\x63oda/v1/got.proto\x12\x07\x63oda.v1\x1a\x16\x63oda/v1/clinical.proto\"\x86\x01\n\tCandidate\x12\r\n\x05index\x18\x01 \x01(\r\x12$\n\tfield_key\x18\x02 \x01(\x0e\x32\x11.coda.v1.FieldKey\x12\x0c\n\x04text\x18\x03 \x01(\t\x12\x1a\n\x12source_thought_ids\x18\x04 \x03(\t\x12\x1a\n\x12generated_by_model\x18\x05 \x01(\t\"t\n\x0eScoreBreakdown\x12\x11\n\trelevance\x18\x01 \x01(\x02\x12\x13\n\x0b\x63onsistency\x18\x02 \x01(\x02\x12\x12\n\nredundancy\x18\x03 \x01(\x02\x12\x11\n\taggregate\x18\x04 \x01(\x02\x12\x13\n\x0bjudge_model\x18\x05 \x01(\t\"\xe0\x01\n\x0c\x43\x61ndidateSet\x12\x17\n\x0f\x63onsultation_id\x18\x01 \x01(\t\x12\x15\n\rrun_config_id\x18\x02 \x01(\t\x12$\n\tfield_key\x18\x03 \x01(\x0e\x32\x11.coda.v1.FieldKey\x12\x11\n\titeration\x18\x04 \x01(\r\x12&\n\ncandidates\x18\x05 \x03(\x0b\x32\x12.coda.v1.Candidate\x12\'\n\x06scores\x18\x06 \x03(\x0b\x32\x17.coda.v1.ScoreBreakdown\x12\x16\n\x0eselected_index\x18\x07 \x01(\r\"\xbc\x01\n\x0fRefinementTrace\x12\x17\n\x0f\x63onsultation_id\x18\x01 \x01(\t\x12\x15\n\rrun_config_id\x18\x02 \x01(\t\x12$\n\tfield_key\x18\x03 \x01(\x0e\x32\x11.coda.v1.FieldKey\x12)\n\niterations\x18\x04 \x03(\x0b\x32\x15.coda.v1.CandidateSet\x12(\n\x0b\x66inal_value\x18\x05 \x01(\x0b\x32\x13.coda.v1.FieldValueB*Z(coda/go/internal/genproto/coda/v1;codev1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'coda.v1.got_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z(coda/go/internal/genproto/coda/v1;codev1'
  _globals['_CANDIDATE']._serialized_start=55
  _globals['_CANDIDATE']._serialized_end=189
  _globals['_SCOREBREAKDOWN']._serialized_start=191
  _globals['_SCOREBREAKDOWN']._serialized_end=307
  _globals['_CANDIDATESET']._serialized_start=310
  _globals['_CANDIDATESET']._serialized_end=534
  _globals['_REFINEMENTTRACE']._serialized_start=537
  _globals['_REFINEMENTTRACE']._serialized_end=725
# @@protoc_insertion_point(module_scope)
