# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: coda/v1/runconfig.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'coda/v1/runconfig.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17\x63oda/v1/runconfig.proto\x12\x07\x63oda.v1\"K\n\rScorerWeights\x12\x11\n\trelevance\x18\x01 \x01(\x02\x12\x13\n\x0b\x63onsistency\x18\x02 \x01(\x02\x12\x12\n\nredundancy\x18\x03 \x01(\x02\"\xce\x03\n\tRunConfig\x12\x0b\n\x03\x61rm\x18\x01 \x01(\t\x12\x16\n\x0eschema_version\x18\x02 \x01(\r\x12\x12\n\nbase_model\x18\x03 \x01(\t\x12\x13\n\x0bjudge_model\x18\x04 \x01(\t\x12\x18\n\x10structural_model\x18\x05 \x01(\t\x12\x13\n\x0b\x65mbed_model\x18\x06 \x01(\t\x12\x13\n\x0b\x61sr_backend\x18\x07 \x01(\t\x12\x11\n\tasr_model\x18\x08 \x01(\t\x12\x13\n\x0bgot_enabled\x18\t \x01(\x08\x12\x14\n\x0cn_candidates\x18\n \x01(\r\x12\x14\n\x0ck_iterations\x18\x0b \x01(\r\x12\x1d\n\x15graph_context_enabled\x18\x0c \x01(\x08\x12\x12\n\nkg_enabled\x18\r \x01(\x08\x12\x12\n\nkg_backend\x18\x0e \x01(\t\x12.\n\x0escorer_weights\x18\x0f \x01(\x0b\x32\x16.coda.v1.ScorerWeights\x12\x13\n\x0btemperature\x18\x10 \x01(\x02\x12\r\n\x05top_p\x18\x11 \x01(\x02\x12\x0c\n\x04seed\x18\x12 \x01(\r\x12\x17\n\x0fprompt_set_hash\x18\x13 \x01(\t\x12\x19\n\x11redaction_enabled\x18\x14 \x01(\x08\x42*Z(coda/go/internal/genproto/coda/v1;codev1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'coda.v1.runconfig_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z(coda/go/internal/genproto/coda/v1;codev1'
  _globals['_SCORERWEIGHTS']._serialized_start=36
  _globals['_SCORERWEIGHTS']._serialized_end=111
  _globals['_RUNCONFIG']._serialized_start=114
  _globals['_RUNCONFIG']._serialized_end=576
# @@protoc_insertion_point(module_scope)
