# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: coda/v1/transcript.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'coda/v1/transcript.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18\x63oda/v1/transcript.proto\x12\x07\x63oda.v1\"f\n\x04Word\x12\x0c\n\x04text\x18\x01 \x01(\t\x12\x10\n\x08start_ms\x18\x02 \x01(\r\x12\x0e\n\x06\x65nd_ms\x18\x03 \x01(\r\x12\x12\n\nconfidence\x18\x04 \x01(\x02\x12\x1a\n\x12speaker_cluster_id\x18\x05 \x01(\t\"e\n\x0eSpeakerCluster\x12\x12\n\ncluster_id\x18\x01 \x01(\t\x12+\n\rassigned_role\x18\x02 \x01(\x0e\x32\x14.coda.v1.SpeakerRole\x12\x12\n\nconfidence\x18\x03 \x01(\x02\"\xc0\x01\n\x04Turn\x12\x12\n\nturn_index\x18\x01 \x01(\r\x12+\n\rspeaker_label\x18\x02 \x01(\x0e\x32\x14.coda.v1.SpeakerRole\x12\x10\n\x08start_ms\x18\x03 \x01(\r\x12\x0e\n\x06\x65nd_ms\x18\x04 \x01(\r\x12\x0c\n\x04text\x18\x05 \x01(\t\x12\x15\n\rtext_redacted\x18\x06 \x01(\t\x12\x12\n\nconfidence\x18\x07 \x01(\x02\x12\x1c\n\x05words\x18\x08 \x03(\x0b\x32\r.coda.v1.Word\"\xfb\x01\n\nTranscript\x12\x17\n\x0f\x63onsultation_id\x18\x01 \x01(\t\x12\x15\n\rrun_config_id\x18\x02 \x01(\t\x12\x10\n\x08language\x18\x03 \x01(\t\x12\x13\n\x0b\x61sr_backend\x18\x04 \x01(\t\x12\x11\n\tasr_model\x18\x05 \x01(\t\x12\x1c\n\x05turns\x18\x06 \x03(\x0b\x32\r.coda.v1.Turn\x12\x31\n\x10speaker_clusters\x18\x07 \x03(\x0b\x32\x17.coda.v1.SpeakerCluster\x12\x10\n\x03wer\x18\x08 \x01(\x02H\x00\x88\x01\x01\x12\x10\n\x03\x64\x65r\x18\t \x01(\x02H\x01\x88\x01\x01\x42\x06\n\x04_werB\x06\n\x04_der*x\n\x0bSpeakerRole\x12\x1c\n\x18SPEAKER_ROLE_UNSPECIFIED\x10\x00\x12\x17\n\x13SPEAKER_ROLE_DOCTOR\x10\x01\x12\x18\n\x14SPEAKER_ROLE_PATIENT\x10\x02\x12\x18\n\x14SPEAKER_ROLE_UNKNOWN\x10\x03\x42*Z(coda/go/internal/genproto/coda/v1;codev1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'coda.v1.transcript_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z(coda/go/internal/genproto/coda/v1;codev1'
  _globals['_SPEAKERROLE']._serialized_start=693
  _globals['_SPEAKERROLE']._serialized_end=813
  _globals['_WORD']._serialized_start=37
  _globals['_WORD']._serialized_end=139
  _globals['_SPEAKERCLUSTER']._serialized_start=141
  _globals['_SPEAKERCLUSTER']._serialized_end=242
  _globals['_TURN']._serialized_start=245
  _globals['_TURN']._serialized_end=437
  _globals['_TRANSCRIPT']._serialized_start=440
  _globals['_TRANSCRIPT']._serialized_end=691
# @@protoc_insertion_point(module_scope)
