// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: artifacts.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createArtifact = `-- name: CreateArtifact :one
INSERT INTO artifacts (consultation_id, stage, run_config_id, kind, uri, sha256, bytes, content_type)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, consultation_id, stage, run_config_id, kind, uri, sha256, bytes, content_type, created_at
`

type CreateArtifactParams struct {
	ConsultationID uuid.UUID `db:"consultation_id" json:"consultation_id"`
	Stage          string    `db:"stage" json:"stage"`
	RunConfigID    uuid.UUID `db:"run_config_id" json:"run_config_id"`
	Kind           string    `db:"kind" json:"kind"`
	Uri            string    `db:"uri" json:"uri"`
	Sha256         string    `db:"sha256" json:"sha256"`
	Bytes          int64     `db:"bytes" json:"bytes"`
	ContentType    string    `db:"content_type" json:"content_type"`
}

func (q *Queries) CreateArtifact(ctx context.Context, arg CreateArtifactParams) (*Artifact, error) {
	row := q.db.QueryRow(ctx, createArtifact,
		arg.ConsultationID,
		arg.Stage,
		arg.RunConfigID,
		arg.Kind,
		arg.Uri,
		arg.Sha256,
		arg.Bytes,
		arg.ContentType,
	)
	var i Artifact
	err := row.Scan(
		&i.ID,
		&i.ConsultationID,
		&i.Stage,
		&i.RunConfigID,
		&i.Kind,
		&i.Uri,
		&i.Sha256,
		&i.Bytes,
		&i.ContentType,
		&i.CreatedAt,
	)
	return &i, err
}

const getArtifactByURI = `-- name: GetArtifactByURI :one
SELECT id, consultation_id, stage, run_config_id, kind, uri, sha256, bytes, content_type, created_at FROM artifacts WHERE uri = $1
`

// Orphan detection for the retention sweep: a MinIO object with no
// artifacts row is unreferenced.
func (q *Queries) GetArtifactByURI(ctx context.Context, uri string) (*Artifact, error) {
	row := q.db.QueryRow(ctx, getArtifactByURI, uri)
	var i Artifact
	err := row.Scan(
		&i.ID,
		&i.ConsultationID,
		&i.Stage,
		&i.RunConfigID,
		&i.Kind,
		&i.Uri,
		&i.Sha256,
		&i.Bytes,
		&i.ContentType,
		&i.CreatedAt,
	)
	return &i, err
}

const listArtifactsByConsultation = `-- name: ListArtifactsByConsultation :many
SELECT id, consultation_id, stage, run_config_id, kind, uri, sha256, bytes, content_type, created_at
FROM artifacts
WHERE consultation_id = $1
  AND ($2::uuid IS NULL OR run_config_id = $2)
ORDER BY created_at
`

type ListArtifactsByConsultationParams struct {
	ConsultationID uuid.UUID   `db:"consultation_id" json:"consultation_id"`
	RunConfigID    pgtype.UUID `db:"run_config_id" json:"run_config_id"`
}

// Query pattern: fetch full pipeline artifacts for one consultation.
// Pass run_config_id = NULL to fetch across every arm.
func (q *Queries) ListArtifactsByConsultation(ctx context.Context, arg ListArtifactsByConsultationParams) ([]*Artifact, error) {
	rows, err := q.db.Query(ctx, listArtifactsByConsultation, arg.ConsultationID, arg.RunConfigID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*Artifact
	for rows.Next() {
		var i Artifact
		if err := rows.Scan(
			&i.ID,
			&i.ConsultationID,
			&i.Stage,
			&i.RunConfigID,
			&i.Kind,
			&i.Uri,
			&i.Sha256,
			&i.Bytes,
			&i.ContentType,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertArtifact = `-- name: UpsertArtifact :one
INSERT INTO artifacts (consultation_id, stage, run_config_id, kind, uri, sha256, bytes, content_type)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
ON CONFLICT (uri) DO UPDATE SET uri = EXCLUDED.uri
RETURNING id, consultation_id, stage, run_config_id, kind, uri, sha256, bytes, content_type, created_at
`

type UpsertArtifactParams struct {
	ConsultationID uuid.UUID `db:"consultation_id" json:"consultation_id"`
	Stage          string    `db:"stage" json:"stage"`
	RunConfigID    uuid.UUID `db:"run_config_id" json:"run_config_id"`
	Kind           string    `db:"kind" json:"kind"`
	Uri            string    `db:"uri" json:"uri"`
	Sha256         string    `db:"sha256" json:"sha256"`
	Bytes          int64     `db:"bytes" json:"bytes"`
	ContentType    string    `db:"content_type" json:"content_type"`
}

// Artifact keys are immutable (§3.3), so a conflict on uri means a
// *duplicate delivery* of the same stage result, not a changed artifact —
// at-least-once delivery (ADR-0007) makes that routine. DO UPDATE with a
// no-op assignment (rather than DO NOTHING) so the existing row is still
// RETURNINGed and the caller has one code path.
func (q *Queries) UpsertArtifact(ctx context.Context, arg UpsertArtifactParams) (*Artifact, error) {
	row := q.db.QueryRow(ctx, upsertArtifact,
		arg.ConsultationID,
		arg.Stage,
		arg.RunConfigID,
		arg.Kind,
		arg.Uri,
		arg.Sha256,
		arg.Bytes,
		arg.ContentType,
	)
	var i Artifact
	err := row.Scan(
		&i.ID,
		&i.ConsultationID,
		&i.Stage,
		&i.RunConfigID,
		&i.Kind,
		&i.Uri,
		&i.Sha256,
		&i.Bytes,
		&i.ContentType,
		&i.CreatedAt,
	)
	return &i, err
}
