// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: audit_log.sql

package sqlc

import (
	"context"
	"net/netip"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createAuditLogEntry = `-- name: CreateAuditLogEntry :one
INSERT INTO audit_log (org_id, actor_user_id, actor_service, action, resource_type, resource_id, before, after, trace_id, ip, outcome)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
RETURNING id, org_id, actor_user_id, actor_service, action, resource_type, resource_id, before, after, trace_id, ip, at, outcome
`

type CreateAuditLogEntryParams struct {
	OrgID        uuid.UUID   `db:"org_id" json:"org_id"`
	ActorUserID  pgtype.UUID `db:"actor_user_id" json:"actor_user_id"`
	ActorService pgtype.Text `db:"actor_service" json:"actor_service"`
	Action       string      `db:"action" json:"action"`
	ResourceType string      `db:"resource_type" json:"resource_type"`
	ResourceID   string      `db:"resource_id" json:"resource_id"`
	Before       []byte      `db:"before" json:"before"`
	After        []byte      `db:"after" json:"after"`
	TraceID      string      `db:"trace_id" json:"trace_id"`
	Ip           *netip.Addr `db:"ip" json:"ip"`
	Outcome      string      `db:"outcome" json:"outcome"`
}

func (q *Queries) CreateAuditLogEntry(ctx context.Context, arg CreateAuditLogEntryParams) (*AuditLog, error) {
	row := q.db.QueryRow(ctx, createAuditLogEntry,
		arg.OrgID,
		arg.ActorUserID,
		arg.ActorService,
		arg.Action,
		arg.ResourceType,
		arg.ResourceID,
		arg.Before,
		arg.After,
		arg.TraceID,
		arg.Ip,
		arg.Outcome,
	)
	var i AuditLog
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.ActorUserID,
		&i.ActorService,
		&i.Action,
		&i.ResourceType,
		&i.ResourceID,
		&i.Before,
		&i.After,
		&i.TraceID,
		&i.Ip,
		&i.At,
		&i.Outcome,
	)
	return &i, err
}

const listAuditLogByOrg = `-- name: ListAuditLogByOrg :many
SELECT id, org_id, actor_user_id, actor_service, action, resource_type, resource_id, before, after, trace_id, ip, at, outcome FROM audit_log WHERE org_id = $1 ORDER BY at DESC LIMIT $2 OFFSET $3
`

type ListAuditLogByOrgParams struct {
	OrgID  uuid.UUID `db:"org_id" json:"org_id"`
	Limit  int32     `db:"limit" json:"limit"`
	Offset int32     `db:"offset" json:"offset"`
}

func (q *Queries) ListAuditLogByOrg(ctx context.Context, arg ListAuditLogByOrgParams) ([]*AuditLog, error) {
	rows, err := q.db.Query(ctx, listAuditLogByOrg, arg.OrgID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*AuditLog
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.ActorUserID,
			&i.ActorService,
			&i.Action,
			&i.ResourceType,
			&i.ResourceID,
			&i.Before,
			&i.After,
			&i.TraceID,
			&i.Ip,
			&i.At,
			&i.Outcome,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAuditLogByResource = `-- name: ListAuditLogByResource :many
SELECT id, org_id, actor_user_id, actor_service, action, resource_type, resource_id, before, after, trace_id, ip, at, outcome FROM audit_log WHERE resource_type = $1 AND resource_id = $2 ORDER BY at DESC
`

type ListAuditLogByResourceParams struct {
	ResourceType string `db:"resource_type" json:"resource_type"`
	ResourceID   string `db:"resource_id" json:"resource_id"`
}

func (q *Queries) ListAuditLogByResource(ctx context.Context, arg ListAuditLogByResourceParams) ([]*AuditLog, error) {
	rows, err := q.db.Query(ctx, listAuditLogByResource, arg.ResourceType, arg.ResourceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*AuditLog
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.ActorUserID,
			&i.ActorService,
			&i.Action,
			&i.ResourceType,
			&i.ResourceID,
			&i.Before,
			&i.After,
			&i.TraceID,
			&i.Ip,
			&i.At,
			&i.Outcome,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
