// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: clinical_notes.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const approveClinicalNote = `-- name: ApproveClinicalNote :one
UPDATE clinical_notes
SET status = 'approved', approved_by = $2, approved_at = now()
WHERE id = $1
RETURNING id, consultation_id, run_config_id, version, status, note, approved_by, approved_at, created_at, updated_at
`

type ApproveClinicalNoteParams struct {
	ID         uuid.UUID   `db:"id" json:"id"`
	ApprovedBy pgtype.UUID `db:"approved_by" json:"approved_by"`
}

// No auto-save before doctor approval (§7.5) — this is the only sanctioned
// transition into status='approved', and it is always an explicit,
// authenticated call from the API layer.
func (q *Queries) ApproveClinicalNote(ctx context.Context, arg ApproveClinicalNoteParams) (*ClinicalNote, error) {
	row := q.db.QueryRow(ctx, approveClinicalNote, arg.ID, arg.ApprovedBy)
	var i ClinicalNote
	err := row.Scan(
		&i.ID,
		&i.ConsultationID,
		&i.RunConfigID,
		&i.Version,
		&i.Status,
		&i.Note,
		&i.ApprovedBy,
		&i.ApprovedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const createClinicalNote = `-- name: CreateClinicalNote :one
INSERT INTO clinical_notes (consultation_id, run_config_id, version, status, note)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, consultation_id, run_config_id, version, status, note, approved_by, approved_at, created_at, updated_at
`

type CreateClinicalNoteParams struct {
	ConsultationID uuid.UUID `db:"consultation_id" json:"consultation_id"`
	RunConfigID    uuid.UUID `db:"run_config_id" json:"run_config_id"`
	Version        int32     `db:"version" json:"version"`
	Status         string    `db:"status" json:"status"`
	Note           []byte    `db:"note" json:"note"`
}

func (q *Queries) CreateClinicalNote(ctx context.Context, arg CreateClinicalNoteParams) (*ClinicalNote, error) {
	row := q.db.QueryRow(ctx, createClinicalNote,
		arg.ConsultationID,
		arg.RunConfigID,
		arg.Version,
		arg.Status,
		arg.Note,
	)
	var i ClinicalNote
	err := row.Scan(
		&i.ID,
		&i.ConsultationID,
		&i.RunConfigID,
		&i.Version,
		&i.Status,
		&i.Note,
		&i.ApprovedBy,
		&i.ApprovedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const getClinicalNoteForConsultationAndRunConfig = `-- name: GetClinicalNoteForConsultationAndRunConfig :one
SELECT id, consultation_id, run_config_id, version, status, note, approved_by, approved_at, created_at, updated_at FROM clinical_notes
WHERE consultation_id = $1 AND run_config_id = $2
ORDER BY version DESC
LIMIT 1
`

type GetClinicalNoteForConsultationAndRunConfigParams struct {
	ConsultationID uuid.UUID `db:"consultation_id" json:"consultation_id"`
	RunConfigID    uuid.UUID `db:"run_config_id" json:"run_config_id"`
}

// Query pattern: fetch full pipeline artifacts for one consultation.
func (q *Queries) GetClinicalNoteForConsultationAndRunConfig(ctx context.Context, arg GetClinicalNoteForConsultationAndRunConfigParams) (*ClinicalNote, error) {
	row := q.db.QueryRow(ctx, getClinicalNoteForConsultationAndRunConfig, arg.ConsultationID, arg.RunConfigID)
	var i ClinicalNote
	err := row.Scan(
		&i.ID,
		&i.ConsultationID,
		&i.RunConfigID,
		&i.Version,
		&i.Status,
		&i.Note,
		&i.ApprovedBy,
		&i.ApprovedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}
