// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: consent_records.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createConsentRecord = `-- name: CreateConsentRecord :one
INSERT INTO consent_records (org_id, subject_ref, consent_type, granted_at, granted_by, artifact_uri)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, org_id, subject_ref, consent_type, granted_at, granted_by, scope, artifact_uri, revoked_at, created_at, updated_at
`

type CreateConsentRecordParams struct {
	OrgID       uuid.UUID          `db:"org_id" json:"org_id"`
	SubjectRef  string             `db:"subject_ref" json:"subject_ref"`
	ConsentType string             `db:"consent_type" json:"consent_type"`
	GrantedAt   pgtype.Timestamptz `db:"granted_at" json:"granted_at"`
	GrantedBy   uuid.UUID          `db:"granted_by" json:"granted_by"`
	ArtifactUri pgtype.Text        `db:"artifact_uri" json:"artifact_uri"`
}

func (q *Queries) CreateConsentRecord(ctx context.Context, arg CreateConsentRecordParams) (*ConsentRecord, error) {
	row := q.db.QueryRow(ctx, createConsentRecord,
		arg.OrgID,
		arg.SubjectRef,
		arg.ConsentType,
		arg.GrantedAt,
		arg.GrantedBy,
		arg.ArtifactUri,
	)
	var i ConsentRecord
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.SubjectRef,
		&i.ConsentType,
		&i.GrantedAt,
		&i.GrantedBy,
		&i.Scope,
		&i.ArtifactUri,
		&i.RevokedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const getConsentRecord = `-- name: GetConsentRecord :one
SELECT id, org_id, subject_ref, consent_type, granted_at, granted_by, scope, artifact_uri, revoked_at, created_at, updated_at FROM consent_records WHERE id = $1
`

func (q *Queries) GetConsentRecord(ctx context.Context, id uuid.UUID) (*ConsentRecord, error) {
	row := q.db.QueryRow(ctx, getConsentRecord, id)
	var i ConsentRecord
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.SubjectRef,
		&i.ConsentType,
		&i.GrantedAt,
		&i.GrantedBy,
		&i.Scope,
		&i.ArtifactUri,
		&i.RevokedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const revokeConsentRecord = `-- name: RevokeConsentRecord :one
UPDATE consent_records SET revoked_at = now() WHERE id = $1 RETURNING id, org_id, subject_ref, consent_type, granted_at, granted_by, scope, artifact_uri, revoked_at, created_at, updated_at
`

func (q *Queries) RevokeConsentRecord(ctx context.Context, id uuid.UUID) (*ConsentRecord, error) {
	row := q.db.QueryRow(ctx, revokeConsentRecord, id)
	var i ConsentRecord
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.SubjectRef,
		&i.ConsentType,
		&i.GrantedAt,
		&i.GrantedBy,
		&i.Scope,
		&i.ArtifactUri,
		&i.RevokedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}
