// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: consultations.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createConsultation = `-- name: CreateConsultation :one
INSERT INTO consultations (
    org_id, owner_user_id, consent_record_id, consent_obtained, consent_method,
    consent_recorded_at, language
)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, org_id, owner_user_id, consent_record_id, consent_obtained, consent_method, consent_recorded_at, state, language, source_audio_uri, audio_sha256, duration_sec, cancel_requested, erased_at, created_at, updated_at
`

type CreateConsultationParams struct {
	OrgID             uuid.UUID          `db:"org_id" json:"org_id"`
	OwnerUserID       uuid.UUID          `db:"owner_user_id" json:"owner_user_id"`
	ConsentRecordID   uuid.UUID          `db:"consent_record_id" json:"consent_record_id"`
	ConsentObtained   bool               `db:"consent_obtained" json:"consent_obtained"`
	ConsentMethod     pgtype.Text        `db:"consent_method" json:"consent_method"`
	ConsentRecordedAt pgtype.Timestamptz `db:"consent_recorded_at" json:"consent_recorded_at"`
	Language          string             `db:"language" json:"language"`
}

func (q *Queries) CreateConsultation(ctx context.Context, arg CreateConsultationParams) (*Consultation, error) {
	row := q.db.QueryRow(ctx, createConsultation,
		arg.OrgID,
		arg.OwnerUserID,
		arg.ConsentRecordID,
		arg.ConsentObtained,
		arg.ConsentMethod,
		arg.ConsentRecordedAt,
		arg.Language,
	)
	var i Consultation
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.OwnerUserID,
		&i.ConsentRecordID,
		&i.ConsentObtained,
		&i.ConsentMethod,
		&i.ConsentRecordedAt,
		&i.State,
		&i.Language,
		&i.SourceAudioUri,
		&i.AudioSha256,
		&i.DurationSec,
		&i.CancelRequested,
		&i.ErasedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const eraseConsultation = `-- name: EraseConsultation :one
UPDATE consultations
SET source_audio_uri = NULL,
    audio_sha256 = NULL,
    erased_at = now()
WHERE id = $1
RETURNING id, org_id, owner_user_id, consent_record_id, consent_obtained, consent_method, consent_recorded_at, state, language, source_audio_uri, audio_sha256, duration_sec, cancel_requested, erased_at, created_at, updated_at
`

// DPDP erasure on consent withdrawal (§7.2): nulls the PII-bearing columns
// and sets the tombstone timestamp. The row itself is retained.
func (q *Queries) EraseConsultation(ctx context.Context, id uuid.UUID) (*Consultation, error) {
	row := q.db.QueryRow(ctx, eraseConsultation, id)
	var i Consultation
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.OwnerUserID,
		&i.ConsentRecordID,
		&i.ConsentObtained,
		&i.ConsentMethod,
		&i.ConsentRecordedAt,
		&i.State,
		&i.Language,
		&i.SourceAudioUri,
		&i.AudioSha256,
		&i.DurationSec,
		&i.CancelRequested,
		&i.ErasedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const getConsultation = `-- name: GetConsultation :one
SELECT id, org_id, owner_user_id, consent_record_id, consent_obtained, consent_method, consent_recorded_at, state, language, source_audio_uri, audio_sha256, duration_sec, cancel_requested, erased_at, created_at, updated_at FROM consultations WHERE id = $1
`

func (q *Queries) GetConsultation(ctx context.Context, id uuid.UUID) (*Consultation, error) {
	row := q.db.QueryRow(ctx, getConsultation, id)
	var i Consultation
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.OwnerUserID,
		&i.ConsentRecordID,
		&i.ConsentObtained,
		&i.ConsentMethod,
		&i.ConsentRecordedAt,
		&i.State,
		&i.Language,
		&i.SourceAudioUri,
		&i.AudioSha256,
		&i.DurationSec,
		&i.CancelRequested,
		&i.ErasedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const listConsultationsByOrgAndState = `-- name: ListConsultationsByOrgAndState :many
SELECT id, org_id, owner_user_id, consent_record_id, consent_obtained, consent_method, consent_recorded_at, state, language, source_audio_uri, audio_sha256, duration_sec, cancel_requested, erased_at, created_at, updated_at
FROM consultations
WHERE org_id = $1
  AND ($4::text IS NULL OR state = $4::text)
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListConsultationsByOrgAndStateParams struct {
	OrgID  uuid.UUID   `db:"org_id" json:"org_id"`
	Limit  int32       `db:"limit" json:"limit"`
	Offset int32       `db:"offset" json:"offset"`
	State  pgtype.Text `db:"state" json:"state"`
}

// Query pattern: list consultations by org with a status filter.
// Pass state = NULL to list every state for the org.
func (q *Queries) ListConsultationsByOrgAndState(ctx context.Context, arg ListConsultationsByOrgAndStateParams) ([]*Consultation, error) {
	rows, err := q.db.Query(ctx, listConsultationsByOrgAndState,
		arg.OrgID,
		arg.Limit,
		arg.Offset,
		arg.State,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*Consultation
	for rows.Next() {
		var i Consultation
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.OwnerUserID,
			&i.ConsentRecordID,
			&i.ConsentObtained,
			&i.ConsentMethod,
			&i.ConsentRecordedAt,
			&i.State,
			&i.Language,
			&i.SourceAudioUri,
			&i.AudioSha256,
			&i.DurationSec,
			&i.CancelRequested,
			&i.ErasedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateConsultationState = `-- name: UpdateConsultationState :one
UPDATE consultations SET state = $2 WHERE id = $1 RETURNING id, org_id, owner_user_id, consent_record_id, consent_obtained, consent_method, consent_recorded_at, state, language, source_audio_uri, audio_sha256, duration_sec, cancel_requested, erased_at, created_at, updated_at
`

type UpdateConsultationStateParams struct {
	ID    uuid.UUID `db:"id" json:"id"`
	State string    `db:"state" json:"state"`
}

func (q *Queries) UpdateConsultationState(ctx context.Context, arg UpdateConsultationStateParams) (*Consultation, error) {
	row := q.db.QueryRow(ctx, updateConsultationState, arg.ID, arg.State)
	var i Consultation
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.OwnerUserID,
		&i.ConsentRecordID,
		&i.ConsentObtained,
		&i.ConsentMethod,
		&i.ConsentRecordedAt,
		&i.State,
		&i.Language,
		&i.SourceAudioUri,
		&i.AudioSha256,
		&i.DurationSec,
		&i.CancelRequested,
		&i.ErasedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}
