// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: extractions.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createExtraction = `-- name: CreateExtraction :one
INSERT INTO extractions (
    consultation_id, run_config_id, field_key, value, candidate_set_uri,
    selected_candidate_idx, score_breakdown, iteration
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, consultation_id, run_config_id, field_key, value, candidate_set_uri, selected_candidate_idx, score_breakdown, iteration, created_at
`

type CreateExtractionParams struct {
	ConsultationID       uuid.UUID   `db:"consultation_id" json:"consultation_id"`
	RunConfigID          uuid.UUID   `db:"run_config_id" json:"run_config_id"`
	FieldKey             string      `db:"field_key" json:"field_key"`
	Value                []byte      `db:"value" json:"value"`
	CandidateSetUri      pgtype.Text `db:"candidate_set_uri" json:"candidate_set_uri"`
	SelectedCandidateIdx pgtype.Int4 `db:"selected_candidate_idx" json:"selected_candidate_idx"`
	ScoreBreakdown       []byte      `db:"score_breakdown" json:"score_breakdown"`
	Iteration            int32       `db:"iteration" json:"iteration"`
}

func (q *Queries) CreateExtraction(ctx context.Context, arg CreateExtractionParams) (*Extraction, error) {
	row := q.db.QueryRow(ctx, createExtraction,
		arg.ConsultationID,
		arg.RunConfigID,
		arg.FieldKey,
		arg.Value,
		arg.CandidateSetUri,
		arg.SelectedCandidateIdx,
		arg.ScoreBreakdown,
		arg.Iteration,
	)
	var i Extraction
	err := row.Scan(
		&i.ID,
		&i.ConsultationID,
		&i.RunConfigID,
		&i.FieldKey,
		&i.Value,
		&i.CandidateSetUri,
		&i.SelectedCandidateIdx,
		&i.ScoreBreakdown,
		&i.Iteration,
		&i.CreatedAt,
	)
	return &i, err
}

const listExtractionsByConsultationAndRunConfig = `-- name: ListExtractionsByConsultationAndRunConfig :many
SELECT id, consultation_id, run_config_id, field_key, value, candidate_set_uri, selected_candidate_idx, score_breakdown, iteration, created_at FROM extractions WHERE consultation_id = $1 AND run_config_id = $2 ORDER BY field_key, iteration
`

type ListExtractionsByConsultationAndRunConfigParams struct {
	ConsultationID uuid.UUID `db:"consultation_id" json:"consultation_id"`
	RunConfigID    uuid.UUID `db:"run_config_id" json:"run_config_id"`
}

// Query pattern: fetch full pipeline artifacts for one consultation.
func (q *Queries) ListExtractionsByConsultationAndRunConfig(ctx context.Context, arg ListExtractionsByConsultationAndRunConfigParams) ([]*Extraction, error) {
	rows, err := q.db.Query(ctx, listExtractionsByConsultationAndRunConfig, arg.ConsultationID, arg.RunConfigID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*Extraction
	for rows.Next() {
		var i Extraction
		if err := rows.Scan(
			&i.ID,
			&i.ConsultationID,
			&i.RunConfigID,
			&i.FieldKey,
			&i.Value,
			&i.CandidateSetUri,
			&i.SelectedCandidateIdx,
			&i.ScoreBreakdown,
			&i.Iteration,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
