// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: job_stages.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const claimJobStage = `-- name: ClaimJobStage :one
INSERT INTO job_stages (job_id, stage, idempotency_key, status, attempt)
VALUES ($1, $2, $3, 'running', 1)
ON CONFLICT (idempotency_key) DO NOTHING
RETURNING id, job_id, stage, idempotency_key, status, attempt, result_ref, metrics, started_at, finished_at, created_at, updated_at, percent_complete, step, heartbeat_at, deadline_at, last_error, error_history
`

type ClaimJobStageParams struct {
	JobID          uuid.UUID `db:"job_id" json:"job_id"`
	Stage          string    `db:"stage" json:"stage"`
	IdempotencyKey string    `db:"idempotency_key" json:"idempotency_key"`
}

// Dedupe protocol step 2 (§2.3): claim the row before doing any work.
// ON CONFLICT DO NOTHING means a retry/redelivery for the same
// idempotency_key claims nothing new — the caller falls through to
// GetJobStageByIdempotencyKey to find the existing row's status.
func (q *Queries) ClaimJobStage(ctx context.Context, arg ClaimJobStageParams) (*JobStage, error) {
	row := q.db.QueryRow(ctx, claimJobStage, arg.JobID, arg.Stage, arg.IdempotencyKey)
	var i JobStage
	err := row.Scan(
		&i.ID,
		&i.JobID,
		&i.Stage,
		&i.IdempotencyKey,
		&i.Status,
		&i.Attempt,
		&i.ResultRef,
		&i.Metrics,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PercentComplete,
		&i.Step,
		&i.HeartbeatAt,
		&i.DeadlineAt,
		&i.LastError,
		&i.ErrorHistory,
	)
	return &i, err
}

const completeJobStage = `-- name: CompleteJobStage :one
UPDATE job_stages
SET status = 'succeeded', result_ref = $2, metrics = $3,
    finished_at = now(), percent_complete = 100
WHERE id = $1
RETURNING id, job_id, stage, idempotency_key, status, attempt, result_ref, metrics, started_at, finished_at, created_at, updated_at, percent_complete, step, heartbeat_at, deadline_at, last_error, error_history
`

type CompleteJobStageParams struct {
	ID        uuid.UUID   `db:"id" json:"id"`
	ResultRef pgtype.Text `db:"result_ref" json:"result_ref"`
	Metrics   []byte      `db:"metrics" json:"metrics"`
}

// Terminal success write for one stage. percent_complete is forced to 100
// so a UI reading the last heartbeat doesn't show a succeeded stage at 60%.
func (q *Queries) CompleteJobStage(ctx context.Context, arg CompleteJobStageParams) (*JobStage, error) {
	row := q.db.QueryRow(ctx, completeJobStage, arg.ID, arg.ResultRef, arg.Metrics)
	var i JobStage
	err := row.Scan(
		&i.ID,
		&i.JobID,
		&i.Stage,
		&i.IdempotencyKey,
		&i.Status,
		&i.Attempt,
		&i.ResultRef,
		&i.Metrics,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PercentComplete,
		&i.Step,
		&i.HeartbeatAt,
		&i.DeadlineAt,
		&i.LastError,
		&i.ErrorHistory,
	)
	return &i, err
}

const dispatchJobStage = `-- name: DispatchJobStage :one
INSERT INTO job_stages (job_id, stage, idempotency_key, status, attempt, deadline_at, started_at)
VALUES ($1, $2, $3, 'running', $4, $5, now())
ON CONFLICT (idempotency_key) DO UPDATE
SET job_id = EXCLUDED.job_id,
    status = 'running',
    attempt = EXCLUDED.attempt,
    deadline_at = EXCLUDED.deadline_at,
    started_at = CASE WHEN job_stages.job_id = EXCLUDED.job_id
                       THEN COALESCE(job_stages.started_at, now())
                       ELSE now()
                  END,
    finished_at = NULL,
    heartbeat_at = NULL,
    percent_complete = 0,
    step = NULL,
    last_error = CASE WHEN job_stages.job_id = EXCLUDED.job_id
                       THEN job_stages.last_error
                       ELSE NULL
                  END,
    error_history = CASE WHEN job_stages.job_id = EXCLUDED.job_id
                          THEN job_stages.error_history
                          ELSE '[]'::jsonb
                     END
WHERE job_stages.status <> 'succeeded'
RETURNING id, job_id, stage, idempotency_key, status, attempt, result_ref, metrics, started_at, finished_at, created_at, updated_at, percent_complete, step, heartbeat_at, deadline_at, last_error, error_history
`

type DispatchJobStageParams struct {
	JobID          uuid.UUID          `db:"job_id" json:"job_id"`
	Stage          string             `db:"stage" json:"stage"`
	IdempotencyKey string             `db:"idempotency_key" json:"idempotency_key"`
	Attempt        int32              `db:"attempt" json:"attempt"`
	DeadlineAt     pgtype.Timestamptz `db:"deadline_at" json:"deadline_at"`
}

// Dedupe protocol (§2.3) from the orchestrator's side, as one statement.
//
// A first dispatch inserts. A retry, a reaper re-dispatch, or a restarted
// orchestrator re-running its scan hits the idempotency_key conflict and
// updates the same row in place — attempt/deadline move, started_at and
// error_history are preserved.
//
// RunConfig interning (ADR-0012) means a DIFFERENT job (a resubmit after a
// prior job dead-lettered or failed without this stage ever succeeding) can
// compute the exact same idempotency_key — same consultation, stage,
// run_config_id, and input. Without job_id in the SET list, that row stays
// permanently owned by the old, terminal job: the new job's own
// GET/SSE status view shows no stages at all, while the real work's
// heartbeats and result land invisibly against the old job's row (found
// live: a resubmitted job inherited attempt=4 from its dead-lettered
// predecessor's exhausted 3-attempt budget, and the job actually running
// showed zero progress to its own caller). Reassigning job_id here is what
// makes a resubmit behave like the fresh job it is — the caller only passes
// attempt=1 for it (dispatch.go), since inheriting an already-exhausted
// attempt count would immediately dead-letter a job that never got to run.
// started_at/error_history/last_error are preserved on a genuine same-job
// retry (the common case this dedupe exists for) but reset when ownership
// actually changes hands, so a new job's history doesn't carry a stranger's.
//
// The DO UPDATE ... WHERE guard is the load-bearing part: a row already
// 'succeeded' matches no update, so the statement returns *no rows*. That
// is the caller's signal to skip dispatch entirely and reuse the stored
// result_ref (GetJobStageByIdempotencyKey), which is what stops an
// expensive stage being re-paid for after a crash — and, deliberately,
// what lets a resubmitted job reuse a *successful* predecessor's result
// without recomputing it. It is enforced by the UNIQUE constraint, not by
// orchestrator correctness (ADR-0007).
func (q *Queries) DispatchJobStage(ctx context.Context, arg DispatchJobStageParams) (*JobStage, error) {
	row := q.db.QueryRow(ctx, dispatchJobStage,
		arg.JobID,
		arg.Stage,
		arg.IdempotencyKey,
		arg.Attempt,
		arg.DeadlineAt,
	)
	var i JobStage
	err := row.Scan(
		&i.ID,
		&i.JobID,
		&i.Stage,
		&i.IdempotencyKey,
		&i.Status,
		&i.Attempt,
		&i.ResultRef,
		&i.Metrics,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PercentComplete,
		&i.Step,
		&i.HeartbeatAt,
		&i.DeadlineAt,
		&i.LastError,
		&i.ErrorHistory,
	)
	return &i, err
}

const failJobStage = `-- name: FailJobStage :one
UPDATE job_stages
SET status = $1,
    last_error = $2,
    error_history = error_history || $3::jsonb,
    metrics = $4,
    finished_at = now()
WHERE id = $5
RETURNING id, job_id, stage, idempotency_key, status, attempt, result_ref, metrics, started_at, finished_at, created_at, updated_at, percent_complete, step, heartbeat_at, deadline_at, last_error, error_history
`

type FailJobStageParams struct {
	Status       string    `db:"status" json:"status"`
	LastError    []byte    `db:"last_error" json:"last_error"`
	AttemptError []byte    `db:"attempt_error" json:"attempt_error"`
	Metrics      []byte    `db:"metrics" json:"metrics"`
	ID           uuid.UUID `db:"id" json:"id"`
}

// Records one failed attempt. error_history is *appended* to, never
// replaced — it is the DeadLetter.attempts[] field (§2.5: "carries the
// original envelope, every attempt's error"), and a DLQ message must be
// reconstructible from Postgres after Redis has trimmed the stream.
func (q *Queries) FailJobStage(ctx context.Context, arg FailJobStageParams) (*JobStage, error) {
	row := q.db.QueryRow(ctx, failJobStage,
		arg.Status,
		arg.LastError,
		arg.AttemptError,
		arg.Metrics,
		arg.ID,
	)
	var i JobStage
	err := row.Scan(
		&i.ID,
		&i.JobID,
		&i.Stage,
		&i.IdempotencyKey,
		&i.Status,
		&i.Attempt,
		&i.ResultRef,
		&i.Metrics,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PercentComplete,
		&i.Step,
		&i.HeartbeatAt,
		&i.DeadlineAt,
		&i.LastError,
		&i.ErrorHistory,
	)
	return &i, err
}

const getJobStageByIdempotencyKey = `-- name: GetJobStageByIdempotencyKey :one
SELECT id, job_id, stage, idempotency_key, status, attempt, result_ref, metrics, started_at, finished_at, created_at, updated_at, percent_complete, step, heartbeat_at, deadline_at, last_error, error_history FROM job_stages WHERE idempotency_key = $1
`

// Dedupe protocol step 1 (§2.3): check for an already-succeeded row before
// doing any work.
func (q *Queries) GetJobStageByIdempotencyKey(ctx context.Context, idempotencyKey string) (*JobStage, error) {
	row := q.db.QueryRow(ctx, getJobStageByIdempotencyKey, idempotencyKey)
	var i JobStage
	err := row.Scan(
		&i.ID,
		&i.JobID,
		&i.Stage,
		&i.IdempotencyKey,
		&i.Status,
		&i.Attempt,
		&i.ResultRef,
		&i.Metrics,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PercentComplete,
		&i.Step,
		&i.HeartbeatAt,
		&i.DeadlineAt,
		&i.LastError,
		&i.ErrorHistory,
	)
	return &i, err
}

const getJobStageByJobAndStage = `-- name: GetJobStageByJobAndStage :one
SELECT id, job_id, stage, idempotency_key, status, attempt, result_ref, metrics, started_at, finished_at, created_at, updated_at, percent_complete, step, heartbeat_at, deadline_at, last_error, error_history FROM job_stages
WHERE job_id = $1 AND stage = $2
ORDER BY created_at DESC
LIMIT 1
`

type GetJobStageByJobAndStageParams struct {
	JobID uuid.UUID `db:"job_id" json:"job_id"`
	Stage string    `db:"stage" json:"stage"`
}

// Resolve a result/heartbeat message to its row when the sender echoed a
// stale idempotency_key (a reclaimed message predating an input change).
// Newest first: a stage re-run under a changed input has more than one row.
func (q *Queries) GetJobStageByJobAndStage(ctx context.Context, arg GetJobStageByJobAndStageParams) (*JobStage, error) {
	row := q.db.QueryRow(ctx, getJobStageByJobAndStage, arg.JobID, arg.Stage)
	var i JobStage
	err := row.Scan(
		&i.ID,
		&i.JobID,
		&i.Stage,
		&i.IdempotencyKey,
		&i.Status,
		&i.Attempt,
		&i.ResultRef,
		&i.Metrics,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PercentComplete,
		&i.Step,
		&i.HeartbeatAt,
		&i.DeadlineAt,
		&i.LastError,
		&i.ErrorHistory,
	)
	return &i, err
}

const incrementJobStageAttempt = `-- name: IncrementJobStageAttempt :one
UPDATE job_stages
SET attempt = attempt + 1, status = 'running', started_at = COALESCE(started_at, now())
WHERE id = $1
RETURNING id, job_id, stage, idempotency_key, status, attempt, result_ref, metrics, started_at, finished_at, created_at, updated_at, percent_complete, step, heartbeat_at, deadline_at, last_error, error_history
`

func (q *Queries) IncrementJobStageAttempt(ctx context.Context, id uuid.UUID) (*JobStage, error) {
	row := q.db.QueryRow(ctx, incrementJobStageAttempt, id)
	var i JobStage
	err := row.Scan(
		&i.ID,
		&i.JobID,
		&i.Stage,
		&i.IdempotencyKey,
		&i.Status,
		&i.Attempt,
		&i.ResultRef,
		&i.Metrics,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PercentComplete,
		&i.Step,
		&i.HeartbeatAt,
		&i.DeadlineAt,
		&i.LastError,
		&i.ErrorHistory,
	)
	return &i, err
}

const listJobStagesByJob = `-- name: ListJobStagesByJob :many
SELECT id, job_id, stage, idempotency_key, status, attempt, result_ref, metrics, started_at, finished_at, created_at, updated_at, percent_complete, step, heartbeat_at, deadline_at, last_error, error_history FROM job_stages WHERE job_id = $1 ORDER BY started_at NULLS LAST
`

// Query pattern: fetch a job with its stages — step 2 of 2.
func (q *Queries) ListJobStagesByJob(ctx context.Context, jobID uuid.UUID) ([]*JobStage, error) {
	rows, err := q.db.Query(ctx, listJobStagesByJob, jobID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*JobStage
	for rows.Next() {
		var i JobStage
		if err := rows.Scan(
			&i.ID,
			&i.JobID,
			&i.Stage,
			&i.IdempotencyKey,
			&i.Status,
			&i.Attempt,
			&i.ResultRef,
			&i.Metrics,
			&i.StartedAt,
			&i.FinishedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.PercentComplete,
			&i.Step,
			&i.HeartbeatAt,
			&i.DeadlineAt,
			&i.LastError,
			&i.ErrorHistory,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStalledJobStages = `-- name: ListStalledJobStages :many
SELECT id, job_id, stage, idempotency_key, status, attempt, result_ref, metrics, started_at, finished_at, created_at, updated_at, percent_complete, step, heartbeat_at, deadline_at, last_error, error_history FROM job_stages
WHERE status = 'running'
  AND (
        (deadline_at IS NOT NULL AND deadline_at <= now())
     OR (heartbeat_at IS NOT NULL
         AND heartbeat_at < now() - make_interval(secs => $2::double precision))
     OR (heartbeat_at IS NULL AND started_at IS NOT NULL
         AND started_at < now() - make_interval(secs => $3::double precision))
  )
ORDER BY started_at
LIMIT $1
`

type ListStalledJobStagesParams struct {
	Limit               int32   `db:"limit" json:"limit"`
	HeartbeatGapSeconds float64 `db:"heartbeat_gap_seconds" json:"heartbeat_gap_seconds"`
	StartupGraceSeconds float64 `db:"startup_grace_seconds" json:"startup_grace_seconds"`
}

// §2.4's stall detection, the Postgres half. XAUTOCLAIM finds messages
// idle in the PEL; this finds stages whose *worker* went quiet — past its
// soft deadline (§4.2), or heartbeat-silent for longer than the allowed
// gap even while still inside the visibility window.
func (q *Queries) ListStalledJobStages(ctx context.Context, arg ListStalledJobStagesParams) ([]*JobStage, error) {
	rows, err := q.db.Query(ctx, listStalledJobStages, arg.Limit, arg.HeartbeatGapSeconds, arg.StartupGraceSeconds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*JobStage
	for rows.Next() {
		var i JobStage
		if err := rows.Scan(
			&i.ID,
			&i.JobID,
			&i.Stage,
			&i.IdempotencyKey,
			&i.Status,
			&i.Attempt,
			&i.ResultRef,
			&i.Metrics,
			&i.StartedAt,
			&i.FinishedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.PercentComplete,
			&i.Step,
			&i.HeartbeatAt,
			&i.DeadlineAt,
			&i.LastError,
			&i.ErrorHistory,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordJobStageHeartbeat = `-- name: RecordJobStageHeartbeat :execrows
UPDATE job_stages
SET percent_complete = $3, step = $4, heartbeat_at = now()
WHERE job_id = $1 AND stage = $2 AND status = 'running'
`

type RecordJobStageHeartbeatParams struct {
	JobID           uuid.UUID   `db:"job_id" json:"job_id"`
	Stage           string      `db:"stage" json:"stage"`
	PercentComplete float32     `db:"percent_complete" json:"percent_complete"`
	Step            pgtype.Text `db:"step" json:"step"`
}

// Lands one StageHeartbeat from stage.progress (§2.4). The orchestrator is
// the only sanctioned consumer of stage.* streams (§1.2), so this row is
// how progress reaches go-api's SSE endpoint — it polls Postgres and never
// touches Redis (claude_context.md decision #35).
//
// Only 'running' rows are updated: a heartbeat that arrives after the
// result (reordering is legal on separate streams) must not resurrect a
// finished stage or walk percent_complete back down from 100.
func (q *Queries) RecordJobStageHeartbeat(ctx context.Context, arg RecordJobStageHeartbeatParams) (int64, error) {
	result, err := q.db.Exec(ctx, recordJobStageHeartbeat,
		arg.JobID,
		arg.Stage,
		arg.PercentComplete,
		arg.Step,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateJobStageResult = `-- name: UpdateJobStageResult :one
UPDATE job_stages
SET status = $2, result_ref = $3, metrics = $4, finished_at = now()
WHERE id = $1
RETURNING id, job_id, stage, idempotency_key, status, attempt, result_ref, metrics, started_at, finished_at, created_at, updated_at, percent_complete, step, heartbeat_at, deadline_at, last_error, error_history
`

type UpdateJobStageResultParams struct {
	ID        uuid.UUID   `db:"id" json:"id"`
	Status    string      `db:"status" json:"status"`
	ResultRef pgtype.Text `db:"result_ref" json:"result_ref"`
	Metrics   []byte      `db:"metrics" json:"metrics"`
}

func (q *Queries) UpdateJobStageResult(ctx context.Context, arg UpdateJobStageResultParams) (*JobStage, error) {
	row := q.db.QueryRow(ctx, updateJobStageResult,
		arg.ID,
		arg.Status,
		arg.ResultRef,
		arg.Metrics,
	)
	var i JobStage
	err := row.Scan(
		&i.ID,
		&i.JobID,
		&i.Stage,
		&i.IdempotencyKey,
		&i.Status,
		&i.Attempt,
		&i.ResultRef,
		&i.Metrics,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PercentComplete,
		&i.Step,
		&i.HeartbeatAt,
		&i.DeadlineAt,
		&i.LastError,
		&i.ErrorHistory,
	)
	return &i, err
}
