// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: job_stages.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const claimJobStage = `-- name: ClaimJobStage :one
INSERT INTO job_stages (job_id, stage, idempotency_key, status, attempt)
VALUES ($1, $2, $3, 'running', 1)
ON CONFLICT (idempotency_key) DO NOTHING
RETURNING id, job_id, stage, idempotency_key, status, attempt, result_ref, metrics, started_at, finished_at, created_at, updated_at
`

type ClaimJobStageParams struct {
	JobID          uuid.UUID `db:"job_id" json:"job_id"`
	Stage          string    `db:"stage" json:"stage"`
	IdempotencyKey string    `db:"idempotency_key" json:"idempotency_key"`
}

// Dedupe protocol step 2 (§2.3): claim the row before doing any work.
// ON CONFLICT DO NOTHING means a retry/redelivery for the same
// idempotency_key claims nothing new — the caller falls through to
// GetJobStageByIdempotencyKey to find the existing row's status.
func (q *Queries) ClaimJobStage(ctx context.Context, arg ClaimJobStageParams) (*JobStage, error) {
	row := q.db.QueryRow(ctx, claimJobStage, arg.JobID, arg.Stage, arg.IdempotencyKey)
	var i JobStage
	err := row.Scan(
		&i.ID,
		&i.JobID,
		&i.Stage,
		&i.IdempotencyKey,
		&i.Status,
		&i.Attempt,
		&i.ResultRef,
		&i.Metrics,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const getJobStageByIdempotencyKey = `-- name: GetJobStageByIdempotencyKey :one
SELECT id, job_id, stage, idempotency_key, status, attempt, result_ref, metrics, started_at, finished_at, created_at, updated_at FROM job_stages WHERE idempotency_key = $1
`

// Dedupe protocol step 1 (§2.3): check for an already-succeeded row before
// doing any work.
func (q *Queries) GetJobStageByIdempotencyKey(ctx context.Context, idempotencyKey string) (*JobStage, error) {
	row := q.db.QueryRow(ctx, getJobStageByIdempotencyKey, idempotencyKey)
	var i JobStage
	err := row.Scan(
		&i.ID,
		&i.JobID,
		&i.Stage,
		&i.IdempotencyKey,
		&i.Status,
		&i.Attempt,
		&i.ResultRef,
		&i.Metrics,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const incrementJobStageAttempt = `-- name: IncrementJobStageAttempt :one
UPDATE job_stages
SET attempt = attempt + 1, status = 'running', started_at = COALESCE(started_at, now())
WHERE id = $1
RETURNING id, job_id, stage, idempotency_key, status, attempt, result_ref, metrics, started_at, finished_at, created_at, updated_at
`

func (q *Queries) IncrementJobStageAttempt(ctx context.Context, id uuid.UUID) (*JobStage, error) {
	row := q.db.QueryRow(ctx, incrementJobStageAttempt, id)
	var i JobStage
	err := row.Scan(
		&i.ID,
		&i.JobID,
		&i.Stage,
		&i.IdempotencyKey,
		&i.Status,
		&i.Attempt,
		&i.ResultRef,
		&i.Metrics,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const listJobStagesByJob = `-- name: ListJobStagesByJob :many
SELECT id, job_id, stage, idempotency_key, status, attempt, result_ref, metrics, started_at, finished_at, created_at, updated_at FROM job_stages WHERE job_id = $1 ORDER BY started_at NULLS LAST
`

// Query pattern: fetch a job with its stages — step 2 of 2.
func (q *Queries) ListJobStagesByJob(ctx context.Context, jobID uuid.UUID) ([]*JobStage, error) {
	rows, err := q.db.Query(ctx, listJobStagesByJob, jobID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*JobStage
	for rows.Next() {
		var i JobStage
		if err := rows.Scan(
			&i.ID,
			&i.JobID,
			&i.Stage,
			&i.IdempotencyKey,
			&i.Status,
			&i.Attempt,
			&i.ResultRef,
			&i.Metrics,
			&i.StartedAt,
			&i.FinishedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateJobStageResult = `-- name: UpdateJobStageResult :one
UPDATE job_stages
SET status = $2, result_ref = $3, metrics = $4, finished_at = now()
WHERE id = $1
RETURNING id, job_id, stage, idempotency_key, status, attempt, result_ref, metrics, started_at, finished_at, created_at, updated_at
`

type UpdateJobStageResultParams struct {
	ID        uuid.UUID   `db:"id" json:"id"`
	Status    string      `db:"status" json:"status"`
	ResultRef pgtype.Text `db:"result_ref" json:"result_ref"`
	Metrics   []byte      `db:"metrics" json:"metrics"`
}

func (q *Queries) UpdateJobStageResult(ctx context.Context, arg UpdateJobStageResultParams) (*JobStage, error) {
	row := q.db.QueryRow(ctx, updateJobStageResult,
		arg.ID,
		arg.Status,
		arg.ResultRef,
		arg.Metrics,
	)
	var i JobStage
	err := row.Scan(
		&i.ID,
		&i.JobID,
		&i.Stage,
		&i.IdempotencyKey,
		&i.Status,
		&i.Attempt,
		&i.ResultRef,
		&i.Metrics,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}
