// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: jobs.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createJob = `-- name: CreateJob :one
INSERT INTO jobs (consultation_id, run_config_id, trace_id, eval_run_id)
VALUES ($1, $2, $3, $4)
RETURNING id, consultation_id, run_config_id, state, current_stage, attempt, resume_after, error, trace_id, eval_run_id, created_at, updated_at
`

type CreateJobParams struct {
	ConsultationID uuid.UUID   `db:"consultation_id" json:"consultation_id"`
	RunConfigID    uuid.UUID   `db:"run_config_id" json:"run_config_id"`
	TraceID        string      `db:"trace_id" json:"trace_id"`
	EvalRunID      pgtype.UUID `db:"eval_run_id" json:"eval_run_id"`
}

func (q *Queries) CreateJob(ctx context.Context, arg CreateJobParams) (*Job, error) {
	row := q.db.QueryRow(ctx, createJob,
		arg.ConsultationID,
		arg.RunConfigID,
		arg.TraceID,
		arg.EvalRunID,
	)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.ConsultationID,
		&i.RunConfigID,
		&i.State,
		&i.CurrentStage,
		&i.Attempt,
		&i.ResumeAfter,
		&i.Error,
		&i.TraceID,
		&i.EvalRunID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const getJob = `-- name: GetJob :one
SELECT id, consultation_id, run_config_id, state, current_stage, attempt, resume_after, error, trace_id, eval_run_id, created_at, updated_at FROM jobs WHERE id = $1
`

// Query pattern: fetch a job with its stages — step 1 of 2 (paired with
// ListJobStagesByJob). Two round trips, not a JSON-aggregating join: sqlc
// doesn't need cleverness here and a job's stage count is tiny (asr,
// redact, nlp, export).
func (q *Queries) GetJob(ctx context.Context, id uuid.UUID) (*Job, error) {
	row := q.db.QueryRow(ctx, getJob, id)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.ConsultationID,
		&i.RunConfigID,
		&i.State,
		&i.CurrentStage,
		&i.Attempt,
		&i.ResumeAfter,
		&i.Error,
		&i.TraceID,
		&i.EvalRunID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const incrementJobAttempt = `-- name: IncrementJobAttempt :one
UPDATE jobs SET attempt = attempt + 1 WHERE id = $1 RETURNING id, consultation_id, run_config_id, state, current_stage, attempt, resume_after, error, trace_id, eval_run_id, created_at, updated_at
`

func (q *Queries) IncrementJobAttempt(ctx context.Context, id uuid.UUID) (*Job, error) {
	row := q.db.QueryRow(ctx, incrementJobAttempt, id)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.ConsultationID,
		&i.RunConfigID,
		&i.State,
		&i.CurrentStage,
		&i.Attempt,
		&i.ResumeAfter,
		&i.Error,
		&i.TraceID,
		&i.EvalRunID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const listJobsAwaitingResume = `-- name: ListJobsAwaitingResume :many
SELECT id, consultation_id, run_config_id, state, current_stage, attempt, resume_after, error, trace_id, eval_run_id, created_at, updated_at FROM jobs
WHERE state = $1 AND resume_after IS NOT NULL AND resume_after <= now()
ORDER BY resume_after
`

// Orchestrator resume-scan: quota-parked or retry-backoff jobs whose
// resume_after has elapsed (§2.5 — quota parking is not a retry).
func (q *Queries) ListJobsAwaitingResume(ctx context.Context, state string) ([]*Job, error) {
	rows, err := q.db.Query(ctx, listJobsAwaitingResume, state)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*Job
	for rows.Next() {
		var i Job
		if err := rows.Scan(
			&i.ID,
			&i.ConsultationID,
			&i.RunConfigID,
			&i.State,
			&i.CurrentStage,
			&i.Attempt,
			&i.ResumeAfter,
			&i.Error,
			&i.TraceID,
			&i.EvalRunID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listJobsByConsultation = `-- name: ListJobsByConsultation :many
SELECT id, consultation_id, run_config_id, state, current_stage, attempt, resume_after, error, trace_id, eval_run_id, created_at, updated_at FROM jobs WHERE consultation_id = $1 ORDER BY created_at
`

func (q *Queries) ListJobsByConsultation(ctx context.Context, consultationID uuid.UUID) ([]*Job, error) {
	rows, err := q.db.Query(ctx, listJobsByConsultation, consultationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*Job
	for rows.Next() {
		var i Job
		if err := rows.Scan(
			&i.ID,
			&i.ConsultationID,
			&i.RunConfigID,
			&i.State,
			&i.CurrentStage,
			&i.Attempt,
			&i.ResumeAfter,
			&i.Error,
			&i.TraceID,
			&i.EvalRunID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateJobState = `-- name: UpdateJobState :one
UPDATE jobs
SET state = $2, current_stage = $3, resume_after = $4, error = $5
WHERE id = $1
RETURNING id, consultation_id, run_config_id, state, current_stage, attempt, resume_after, error, trace_id, eval_run_id, created_at, updated_at
`

type UpdateJobStateParams struct {
	ID           uuid.UUID          `db:"id" json:"id"`
	State        string             `db:"state" json:"state"`
	CurrentStage *string            `db:"current_stage" json:"current_stage"`
	ResumeAfter  pgtype.Timestamptz `db:"resume_after" json:"resume_after"`
	Error        []byte             `db:"error" json:"error"`
}

func (q *Queries) UpdateJobState(ctx context.Context, arg UpdateJobStateParams) (*Job, error) {
	row := q.db.QueryRow(ctx, updateJobState,
		arg.ID,
		arg.State,
		arg.CurrentStage,
		arg.ResumeAfter,
		arg.Error,
	)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.ConsultationID,
		&i.RunConfigID,
		&i.State,
		&i.CurrentStage,
		&i.Attempt,
		&i.ResumeAfter,
		&i.Error,
		&i.TraceID,
		&i.EvalRunID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}
