// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: llm_cache.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const createLLMCacheEntry = `-- name: CreateLLMCacheEntry :one
INSERT INTO llm_cache (model, prompt_sha256, response, tokens_in, tokens_out)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (model, prompt_sha256) DO UPDATE SET hit_count = llm_cache.hit_count + 1
RETURNING id, model, prompt_sha256, response, tokens_in, tokens_out, created_at, hit_count
`

type CreateLLMCacheEntryParams struct {
	Model        string `db:"model" json:"model"`
	PromptSha256 string `db:"prompt_sha256" json:"prompt_sha256"`
	Response     []byte `db:"response" json:"response"`
	TokensIn     int32  `db:"tokens_in" json:"tokens_in"`
	TokensOut    int32  `db:"tokens_out" json:"tokens_out"`
}

func (q *Queries) CreateLLMCacheEntry(ctx context.Context, arg CreateLLMCacheEntryParams) (*LlmCache, error) {
	row := q.db.QueryRow(ctx, createLLMCacheEntry,
		arg.Model,
		arg.PromptSha256,
		arg.Response,
		arg.TokensIn,
		arg.TokensOut,
	)
	var i LlmCache
	err := row.Scan(
		&i.ID,
		&i.Model,
		&i.PromptSha256,
		&i.Response,
		&i.TokensIn,
		&i.TokensOut,
		&i.CreatedAt,
		&i.HitCount,
	)
	return &i, err
}

const getLLMCacheEntry = `-- name: GetLLMCacheEntry :one
SELECT id, model, prompt_sha256, response, tokens_in, tokens_out, created_at, hit_count FROM llm_cache WHERE model = $1 AND prompt_sha256 = $2
`

type GetLLMCacheEntryParams struct {
	Model        string `db:"model" json:"model"`
	PromptSha256 string `db:"prompt_sha256" json:"prompt_sha256"`
}

func (q *Queries) GetLLMCacheEntry(ctx context.Context, arg GetLLMCacheEntryParams) (*LlmCache, error) {
	row := q.db.QueryRow(ctx, getLLMCacheEntry, arg.Model, arg.PromptSha256)
	var i LlmCache
	err := row.Scan(
		&i.ID,
		&i.Model,
		&i.PromptSha256,
		&i.Response,
		&i.TokensIn,
		&i.TokensOut,
		&i.CreatedAt,
		&i.HitCount,
	)
	return &i, err
}

const incrementLLMCacheHit = `-- name: IncrementLLMCacheHit :one
UPDATE llm_cache SET hit_count = hit_count + 1 WHERE id = $1 RETURNING id, model, prompt_sha256, response, tokens_in, tokens_out, created_at, hit_count
`

func (q *Queries) IncrementLLMCacheHit(ctx context.Context, id uuid.UUID) (*LlmCache, error) {
	row := q.db.QueryRow(ctx, incrementLLMCacheHit, id)
	var i LlmCache
	err := row.Scan(
		&i.ID,
		&i.Model,
		&i.PromptSha256,
		&i.Response,
		&i.TokensIn,
		&i.TokensOut,
		&i.CreatedAt,
		&i.HitCount,
	)
	return &i, err
}
