// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package sqlc

import (
	"net/netip"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Artifact struct {
	ID             uuid.UUID          `db:"id" json:"id"`
	ConsultationID uuid.UUID          `db:"consultation_id" json:"consultation_id"`
	Stage          string             `db:"stage" json:"stage"`
	RunConfigID    uuid.UUID          `db:"run_config_id" json:"run_config_id"`
	Kind           string             `db:"kind" json:"kind"`
	Uri            string             `db:"uri" json:"uri"`
	Sha256         string             `db:"sha256" json:"sha256"`
	Bytes          int64              `db:"bytes" json:"bytes"`
	ContentType    string             `db:"content_type" json:"content_type"`
	CreatedAt      pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type AuditLog struct {
	ID           uuid.UUID          `db:"id" json:"id"`
	OrgID        uuid.UUID          `db:"org_id" json:"org_id"`
	ActorUserID  pgtype.UUID        `db:"actor_user_id" json:"actor_user_id"`
	ActorService pgtype.Text        `db:"actor_service" json:"actor_service"`
	Action       string             `db:"action" json:"action"`
	ResourceType string             `db:"resource_type" json:"resource_type"`
	ResourceID   string             `db:"resource_id" json:"resource_id"`
	Before       []byte             `db:"before" json:"before"`
	After        []byte             `db:"after" json:"after"`
	TraceID      string             `db:"trace_id" json:"trace_id"`
	Ip           *netip.Addr        `db:"ip" json:"ip"`
	At           pgtype.Timestamptz `db:"at" json:"at"`
	Outcome      string             `db:"outcome" json:"outcome"`
}

type ClinicalNote struct {
	ID             uuid.UUID          `db:"id" json:"id"`
	ConsultationID uuid.UUID          `db:"consultation_id" json:"consultation_id"`
	RunConfigID    uuid.UUID          `db:"run_config_id" json:"run_config_id"`
	Version        int32              `db:"version" json:"version"`
	Status         string             `db:"status" json:"status"`
	Note           []byte             `db:"note" json:"note"`
	ApprovedBy     pgtype.UUID        `db:"approved_by" json:"approved_by"`
	ApprovedAt     pgtype.Timestamptz `db:"approved_at" json:"approved_at"`
	CreatedAt      pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type ConsentRecord struct {
	ID          uuid.UUID          `db:"id" json:"id"`
	OrgID       uuid.UUID          `db:"org_id" json:"org_id"`
	SubjectRef  string             `db:"subject_ref" json:"subject_ref"`
	ConsentType string             `db:"consent_type" json:"consent_type"`
	GrantedAt   pgtype.Timestamptz `db:"granted_at" json:"granted_at"`
	GrantedBy   uuid.UUID          `db:"granted_by" json:"granted_by"`
	Scope       []byte             `db:"scope" json:"scope"`
	ArtifactUri pgtype.Text        `db:"artifact_uri" json:"artifact_uri"`
	RevokedAt   pgtype.Timestamptz `db:"revoked_at" json:"revoked_at"`
	CreatedAt   pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type Consultation struct {
	ID                uuid.UUID          `db:"id" json:"id"`
	OrgID             uuid.UUID          `db:"org_id" json:"org_id"`
	OwnerUserID       uuid.UUID          `db:"owner_user_id" json:"owner_user_id"`
	ConsentRecordID   uuid.UUID          `db:"consent_record_id" json:"consent_record_id"`
	ConsentObtained   bool               `db:"consent_obtained" json:"consent_obtained"`
	ConsentMethod     pgtype.Text        `db:"consent_method" json:"consent_method"`
	ConsentRecordedAt pgtype.Timestamptz `db:"consent_recorded_at" json:"consent_recorded_at"`
	State             string             `db:"state" json:"state"`
	Language          string             `db:"language" json:"language"`
	SourceAudioUri    pgtype.Text        `db:"source_audio_uri" json:"source_audio_uri"`
	AudioSha256       pgtype.Text        `db:"audio_sha256" json:"audio_sha256"`
	DurationSec       pgtype.Float8      `db:"duration_sec" json:"duration_sec"`
	CancelRequested   bool               `db:"cancel_requested" json:"cancel_requested"`
	ErasedAt          pgtype.Timestamptz `db:"erased_at" json:"erased_at"`
	CreatedAt         pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type EvalResult struct {
	ID                  uuid.UUID          `db:"id" json:"id"`
	EvalRunID           uuid.UUID          `db:"eval_run_id" json:"eval_run_id"`
	ConsultationID      uuid.UUID          `db:"consultation_id" json:"consultation_id"`
	RunConfigID         uuid.UUID          `db:"run_config_id" json:"run_config_id"`
	MetricKey           string             `db:"metric_key" json:"metric_key"`
	MetricValue         float64            `db:"metric_value" json:"metric_value"`
	Language            string             `db:"language" json:"language"`
	ReferenceProvenance string             `db:"reference_provenance" json:"reference_provenance"`
	CreatedAt           pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type EvalRun struct {
	ID                uuid.UUID          `db:"id" json:"id"`
	Name              string             `db:"name" json:"name"`
	DatasetSplit      string             `db:"dataset_split" json:"dataset_split"`
	Arm               string             `db:"arm" json:"arm"`
	RunConfigID       uuid.UUID          `db:"run_config_id" json:"run_config_id"`
	StartedAt         pgtype.Timestamptz `db:"started_at" json:"started_at"`
	FinishedAt        pgtype.Timestamptz `db:"finished_at" json:"finished_at"`
	Status            string             `db:"status" json:"status"`
	TotalTokens       int64              `db:"total_tokens" json:"total_tokens"`
	TotalCostEstimate float64            `db:"total_cost_estimate" json:"total_cost_estimate"`
	CreatedAt         pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type Extraction struct {
	ID                   uuid.UUID          `db:"id" json:"id"`
	ConsultationID       uuid.UUID          `db:"consultation_id" json:"consultation_id"`
	RunConfigID          uuid.UUID          `db:"run_config_id" json:"run_config_id"`
	FieldKey             string             `db:"field_key" json:"field_key"`
	Value                []byte             `db:"value" json:"value"`
	CandidateSetUri      pgtype.Text        `db:"candidate_set_uri" json:"candidate_set_uri"`
	SelectedCandidateIdx pgtype.Int4        `db:"selected_candidate_idx" json:"selected_candidate_idx"`
	ScoreBreakdown       []byte             `db:"score_breakdown" json:"score_breakdown"`
	Iteration            int32              `db:"iteration" json:"iteration"`
	CreatedAt            pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type Job struct {
	ID             uuid.UUID          `db:"id" json:"id"`
	ConsultationID uuid.UUID          `db:"consultation_id" json:"consultation_id"`
	RunConfigID    uuid.UUID          `db:"run_config_id" json:"run_config_id"`
	State          string             `db:"state" json:"state"`
	CurrentStage   *string            `db:"current_stage" json:"current_stage"`
	Attempt        int32              `db:"attempt" json:"attempt"`
	ResumeAfter    pgtype.Timestamptz `db:"resume_after" json:"resume_after"`
	Error          []byte             `db:"error" json:"error"`
	TraceID        string             `db:"trace_id" json:"trace_id"`
	EvalRunID      pgtype.UUID        `db:"eval_run_id" json:"eval_run_id"`
	CreatedAt      pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type JobStage struct {
	ID              uuid.UUID          `db:"id" json:"id"`
	JobID           uuid.UUID          `db:"job_id" json:"job_id"`
	Stage           string             `db:"stage" json:"stage"`
	IdempotencyKey  string             `db:"idempotency_key" json:"idempotency_key"`
	Status          string             `db:"status" json:"status"`
	Attempt         int32              `db:"attempt" json:"attempt"`
	ResultRef       pgtype.Text        `db:"result_ref" json:"result_ref"`
	Metrics         []byte             `db:"metrics" json:"metrics"`
	StartedAt       pgtype.Timestamptz `db:"started_at" json:"started_at"`
	FinishedAt      pgtype.Timestamptz `db:"finished_at" json:"finished_at"`
	CreatedAt       pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	PercentComplete float32            `db:"percent_complete" json:"percent_complete"`
	Step            pgtype.Text        `db:"step" json:"step"`
	HeartbeatAt     pgtype.Timestamptz `db:"heartbeat_at" json:"heartbeat_at"`
	DeadlineAt      pgtype.Timestamptz `db:"deadline_at" json:"deadline_at"`
	LastError       []byte             `db:"last_error" json:"last_error"`
	ErrorHistory    []byte             `db:"error_history" json:"error_history"`
}

type LlmCache struct {
	ID           uuid.UUID          `db:"id" json:"id"`
	Model        string             `db:"model" json:"model"`
	PromptSha256 string             `db:"prompt_sha256" json:"prompt_sha256"`
	Response     []byte             `db:"response" json:"response"`
	TokensIn     int32              `db:"tokens_in" json:"tokens_in"`
	TokensOut    int32              `db:"tokens_out" json:"tokens_out"`
	CreatedAt    pgtype.Timestamptz `db:"created_at" json:"created_at"`
	HitCount     int32              `db:"hit_count" json:"hit_count"`
}

type Org struct {
	ID        uuid.UUID          `db:"id" json:"id"`
	Name      string             `db:"name" json:"name"`
	Region    string             `db:"region" json:"region"`
	Settings  []byte             `db:"settings" json:"settings"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type ReferenceLabel struct {
	ID               uuid.UUID          `db:"id" json:"id"`
	ConsultationID   uuid.UUID          `db:"consultation_id" json:"consultation_id"`
	FieldKey         string             `db:"field_key" json:"field_key"`
	Value            []byte             `db:"value" json:"value"`
	Provenance       string             `db:"provenance" json:"provenance"`
	GeneratedByModel pgtype.Text        `db:"generated_by_model" json:"generated_by_model"`
	VerifiedByUser   pgtype.UUID        `db:"verified_by_user" json:"verified_by_user"`
	VerifiedAt       pgtype.Timestamptz `db:"verified_at" json:"verified_at"`
	CreatedAt        pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type RefreshToken struct {
	ID           uuid.UUID          `db:"id" json:"id"`
	UserID       uuid.UUID          `db:"user_id" json:"user_id"`
	FamilyID     uuid.UUID          `db:"family_id" json:"family_id"`
	TokenHash    string             `db:"token_hash" json:"token_hash"`
	IssuedAt     pgtype.Timestamptz `db:"issued_at" json:"issued_at"`
	ExpiresAt    pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
	RevokedAt    pgtype.Timestamptz `db:"revoked_at" json:"revoked_at"`
	ReplacedByID pgtype.UUID        `db:"replaced_by_id" json:"replaced_by_id"`
	CreatedByIp  *netip.Addr        `db:"created_by_ip" json:"created_by_ip"`
	UserAgent    pgtype.Text        `db:"user_agent" json:"user_agent"`
}

type Review struct {
	ID             uuid.UUID          `db:"id" json:"id"`
	ClinicalNoteID uuid.UUID          `db:"clinical_note_id" json:"clinical_note_id"`
	ReviewerUserID uuid.UUID          `db:"reviewer_user_id" json:"reviewer_user_id"`
	StartedAt      pgtype.Timestamptz `db:"started_at" json:"started_at"`
	CompletedAt    pgtype.Timestamptz `db:"completed_at" json:"completed_at"`
	Outcome        pgtype.Text        `db:"outcome" json:"outcome"`
	CreatedAt      pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type ReviewEdit struct {
	ID            uuid.UUID          `db:"id" json:"id"`
	ReviewID      uuid.UUID          `db:"review_id" json:"review_id"`
	FieldKey      string             `db:"field_key" json:"field_key"`
	OriginalValue []byte             `db:"original_value" json:"original_value"`
	EditedValue   []byte             `db:"edited_value" json:"edited_value"`
	EditType      string             `db:"edit_type" json:"edit_type"`
	EditedAt      pgtype.Timestamptz `db:"edited_at" json:"edited_at"`
	EditorUserID  uuid.UUID          `db:"editor_user_id" json:"editor_user_id"`
}

type RunConfig struct {
	ID            uuid.UUID          `db:"id" json:"id"`
	ContentHash   string             `db:"content_hash" json:"content_hash"`
	Arm           string             `db:"arm" json:"arm"`
	Config        []byte             `db:"config" json:"config"`
	SchemaVersion int32              `db:"schema_version" json:"schema_version"`
	CreatedAt     pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type Summary struct {
	ID             uuid.UUID          `db:"id" json:"id"`
	ConsultationID uuid.UUID          `db:"consultation_id" json:"consultation_id"`
	RunConfigID    uuid.UUID          `db:"run_config_id" json:"run_config_id"`
	Text           string             `db:"text" json:"text"`
	RougeL         pgtype.Float8      `db:"rouge_l" json:"rouge_l"`
	Bertscore      pgtype.Float8      `db:"bertscore" json:"bertscore"`
	CreatedAt      pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type Thought struct {
	ID             uuid.UUID          `db:"id" json:"id"`
	ConsultationID uuid.UUID          `db:"consultation_id" json:"consultation_id"`
	RunConfigID    uuid.UUID          `db:"run_config_id" json:"run_config_id"`
	TurnID         uuid.UUID          `db:"turn_id" json:"turn_id"`
	Speaker        string             `db:"speaker" json:"speaker"`
	Text           string             `db:"text" json:"text"`
	Entities       []byte             `db:"entities" json:"entities"`
	Category       string             `db:"category" json:"category"`
	TemporalAnchor pgtype.Text        `db:"temporal_anchor" json:"temporal_anchor"`
	LinkedConcepts []byte             `db:"linked_concepts" json:"linked_concepts"`
	CreatedAt      pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type ThoughtEdge struct {
	ID             uuid.UUID          `db:"id" json:"id"`
	ConsultationID uuid.UUID          `db:"consultation_id" json:"consultation_id"`
	RunConfigID    uuid.UUID          `db:"run_config_id" json:"run_config_id"`
	SrcThoughtID   uuid.UUID          `db:"src_thought_id" json:"src_thought_id"`
	DstThoughtID   uuid.UUID          `db:"dst_thought_id" json:"dst_thought_id"`
	EdgeType       string             `db:"edge_type" json:"edge_type"`
	Weight         float32            `db:"weight" json:"weight"`
	PredictedBy    string             `db:"predicted_by" json:"predicted_by"`
	CreatedAt      pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type Transcript struct {
	ID             uuid.UUID          `db:"id" json:"id"`
	ConsultationID uuid.UUID          `db:"consultation_id" json:"consultation_id"`
	RunConfigID    uuid.UUID          `db:"run_config_id" json:"run_config_id"`
	Uri            string             `db:"uri" json:"uri"`
	AsrBackend     string             `db:"asr_backend" json:"asr_backend"`
	AsrModel       string             `db:"asr_model" json:"asr_model"`
	Wer            pgtype.Float8      `db:"wer" json:"wer"`
	Der            pgtype.Float8      `db:"der" json:"der"`
	Language       string             `db:"language" json:"language"`
	CreatedAt      pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type Turn struct {
	ID           uuid.UUID          `db:"id" json:"id"`
	TranscriptID uuid.UUID          `db:"transcript_id" json:"transcript_id"`
	TurnIndex    int32              `db:"turn_index" json:"turn_index"`
	SpeakerLabel string             `db:"speaker_label" json:"speaker_label"`
	StartMs      int32              `db:"start_ms" json:"start_ms"`
	EndMs        int32              `db:"end_ms" json:"end_ms"`
	Text         string             `db:"text" json:"text"`
	TextRedacted pgtype.Text        `db:"text_redacted" json:"text_redacted"`
	Confidence   pgtype.Float4      `db:"confidence" json:"confidence"`
	CreatedAt    pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type User struct {
	ID           uuid.UUID          `db:"id" json:"id"`
	OrgID        uuid.UUID          `db:"org_id" json:"org_id"`
	Email        string             `db:"email" json:"email"`
	PasswordHash string             `db:"password_hash" json:"password_hash"`
	Role         string             `db:"role" json:"role"`
	Active       bool               `db:"active" json:"active"`
	CreatedAt    pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}
