// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: orgs.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const createOrg = `-- name: CreateOrg :one
INSERT INTO orgs (name, region)
VALUES ($1, $2)
RETURNING id, name, region, settings, created_at, updated_at
`

type CreateOrgParams struct {
	Name   string `db:"name" json:"name"`
	Region string `db:"region" json:"region"`
}

func (q *Queries) CreateOrg(ctx context.Context, arg CreateOrgParams) (*Org, error) {
	row := q.db.QueryRow(ctx, createOrg, arg.Name, arg.Region)
	var i Org
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Region,
		&i.Settings,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const getOrg = `-- name: GetOrg :one
SELECT id, name, region, settings, created_at, updated_at FROM orgs WHERE id = $1
`

func (q *Queries) GetOrg(ctx context.Context, id uuid.UUID) (*Org, error) {
	row := q.db.QueryRow(ctx, getOrg, id)
	var i Org
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Region,
		&i.Settings,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const getOrgByName = `-- name: GetOrgByName :one
SELECT id, name, region, settings, created_at, updated_at FROM orgs WHERE name = $1
`

// No uniqueness constraint on name (an org can rename); used only by the
// idempotent seed script to find its fixed dev org on a re-run.
func (q *Queries) GetOrgByName(ctx context.Context, name string) (*Org, error) {
	row := q.db.QueryRow(ctx, getOrgByName, name)
	var i Org
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Region,
		&i.Settings,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}
