// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	// Query pattern: aggregate eval results by run-config. English and
	// Kannada-English are never averaged into one number (claude_context.md
	// §2) — language stays a GROUP BY key, never collapsed.
	AggregateEvalResultsByRunConfig(ctx context.Context, evalRunID uuid.UUID) ([]*AggregateEvalResultsByRunConfigRow, error)
	// No auto-save before doctor approval (§7.5) — this is the only sanctioned
	// transition into status='approved', and it is always an explicit,
	// authenticated call from the API layer.
	ApproveClinicalNote(ctx context.Context, arg ApproveClinicalNoteParams) (*ClinicalNote, error)
	// Dedupe protocol step 2 (§2.3): claim the row before doing any work.
	// ON CONFLICT DO NOTHING means a retry/redelivery for the same
	// idempotency_key claims nothing new — the caller falls through to
	// GetJobStageByIdempotencyKey to find the existing row's status.
	ClaimJobStage(ctx context.Context, arg ClaimJobStageParams) (*JobStage, error)
	CompleteReview(ctx context.Context, arg CompleteReviewParams) (*Review, error)
	CreateArtifact(ctx context.Context, arg CreateArtifactParams) (*Artifact, error)
	CreateAuditLogEntry(ctx context.Context, arg CreateAuditLogEntryParams) (*AuditLog, error)
	CreateClinicalNote(ctx context.Context, arg CreateClinicalNoteParams) (*ClinicalNote, error)
	CreateConsentRecord(ctx context.Context, arg CreateConsentRecordParams) (*ConsentRecord, error)
	CreateConsultation(ctx context.Context, arg CreateConsultationParams) (*Consultation, error)
	CreateEvalResult(ctx context.Context, arg CreateEvalResultParams) (*EvalResult, error)
	CreateEvalRun(ctx context.Context, arg CreateEvalRunParams) (*EvalRun, error)
	CreateExtraction(ctx context.Context, arg CreateExtractionParams) (*Extraction, error)
	CreateJob(ctx context.Context, arg CreateJobParams) (*Job, error)
	CreateLLMCacheEntry(ctx context.Context, arg CreateLLMCacheEntryParams) (*LlmCache, error)
	CreateOrg(ctx context.Context, arg CreateOrgParams) (*Org, error)
	CreateReferenceLabel(ctx context.Context, arg CreateReferenceLabelParams) (*ReferenceLabel, error)
	CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) (*RefreshToken, error)
	CreateReview(ctx context.Context, arg CreateReviewParams) (*Review, error)
	// The HITL data flywheel (decision #14).
	CreateReviewEdit(ctx context.Context, arg CreateReviewEditParams) (*ReviewEdit, error)
	// Configs are interned on content_hash (ADR-0012): a config that already
	// exists returns the existing row instead of duplicating it.
	CreateRunConfig(ctx context.Context, arg CreateRunConfigParams) (*RunConfig, error)
	CreateSummary(ctx context.Context, arg CreateSummaryParams) (*Summary, error)
	CreateThought(ctx context.Context, arg CreateThoughtParams) (*Thought, error)
	CreateThoughtEdge(ctx context.Context, arg CreateThoughtEdgeParams) (*ThoughtEdge, error)
	CreateTranscript(ctx context.Context, arg CreateTranscriptParams) (*Transcript, error)
	CreateTurn(ctx context.Context, arg CreateTurnParams) (*Turn, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (*User, error)
	// DPDP erasure on consent withdrawal (§7.2): nulls the PII-bearing columns
	// and sets the tombstone timestamp. The row itself is retained.
	EraseConsultation(ctx context.Context, id uuid.UUID) (*Consultation, error)
	// Query pattern: fetch full pipeline artifacts for one consultation.
	GetClinicalNoteForConsultationAndRunConfig(ctx context.Context, arg GetClinicalNoteForConsultationAndRunConfigParams) (*ClinicalNote, error)
	GetConsentRecord(ctx context.Context, id uuid.UUID) (*ConsentRecord, error)
	GetConsultation(ctx context.Context, id uuid.UUID) (*Consultation, error)
	GetEvalRun(ctx context.Context, id uuid.UUID) (*EvalRun, error)
	// Query pattern: fetch a job with its stages — step 1 of 2 (paired with
	// ListJobStagesByJob). Two round trips, not a JSON-aggregating join: sqlc
	// doesn't need cleverness here and a job's stage count is tiny (asr,
	// redact, nlp, export).
	GetJob(ctx context.Context, id uuid.UUID) (*Job, error)
	// Dedupe protocol step 1 (§2.3): check for an already-succeeded row before
	// doing any work.
	GetJobStageByIdempotencyKey(ctx context.Context, idempotencyKey string) (*JobStage, error)
	GetLLMCacheEntry(ctx context.Context, arg GetLLMCacheEntryParams) (*LlmCache, error)
	GetOrg(ctx context.Context, id uuid.UUID) (*Org, error)
	// No uniqueness constraint on name (an org can rename); used only by the
	// idempotent seed script to find its fixed dev org on a re-run.
	GetOrgByName(ctx context.Context, name string) (*Org, error)
	GetRefreshTokenByHash(ctx context.Context, tokenHash string) (*RefreshToken, error)
	GetReview(ctx context.Context, id uuid.UUID) (*Review, error)
	GetRunConfig(ctx context.Context, id uuid.UUID) (*RunConfig, error)
	GetRunConfigByContentHash(ctx context.Context, contentHash string) (*RunConfig, error)
	// Query pattern: fetch full pipeline artifacts for one consultation.
	GetSummaryForConsultationAndRunConfig(ctx context.Context, arg GetSummaryForConsultationAndRunConfigParams) (*Summary, error)
	GetTranscriptForConsultationAndRunConfig(ctx context.Context, arg GetTranscriptForConsultationAndRunConfigParams) (*Transcript, error)
	GetUser(ctx context.Context, id uuid.UUID) (*User, error)
	GetUserByEmail(ctx context.Context, email string) (*User, error)
	IncrementJobAttempt(ctx context.Context, id uuid.UUID) (*Job, error)
	IncrementJobStageAttempt(ctx context.Context, id uuid.UUID) (*JobStage, error)
	IncrementLLMCacheHit(ctx context.Context, id uuid.UUID) (*LlmCache, error)
	// Query pattern: fetch full pipeline artifacts for one consultation.
	// Pass run_config_id = NULL to fetch across every arm.
	ListArtifactsByConsultation(ctx context.Context, arg ListArtifactsByConsultationParams) ([]*Artifact, error)
	ListAuditLogByOrg(ctx context.Context, arg ListAuditLogByOrgParams) ([]*AuditLog, error)
	ListAuditLogByResource(ctx context.Context, arg ListAuditLogByResourceParams) ([]*AuditLog, error)
	// Query pattern: list consultations by org with a status filter.
	// Pass state = NULL to list every state for the org.
	ListConsultationsByOrgAndState(ctx context.Context, arg ListConsultationsByOrgAndStateParams) ([]*Consultation, error)
	// Query pattern: fetch full pipeline artifacts for one consultation.
	ListExtractionsByConsultationAndRunConfig(ctx context.Context, arg ListExtractionsByConsultationAndRunConfigParams) ([]*Extraction, error)
	// Query pattern: fetch a job with its stages — step 2 of 2.
	ListJobStagesByJob(ctx context.Context, jobID uuid.UUID) ([]*JobStage, error)
	// Orchestrator resume-scan: quota-parked or retry-backoff jobs whose
	// resume_after has elapsed (§2.5 — quota parking is not a retry).
	ListJobsAwaitingResume(ctx context.Context, state string) ([]*Job, error)
	ListJobsByConsultation(ctx context.Context, consultationID uuid.UUID) ([]*Job, error)
	ListReferenceLabelsByConsultation(ctx context.Context, consultationID uuid.UUID) ([]*ReferenceLabel, error)
	ListReviewEditsByReview(ctx context.Context, reviewID uuid.UUID) ([]*ReviewEdit, error)
	// Query pattern: fetch full pipeline artifacts for one consultation — the
	// serialized thought graph (nodes from ListThoughtsByConsultationAndRunConfig,
	// edges from here) for the case-study figures (plan.md Phase 6/10).
	ListThoughtEdgesByConsultationAndRunConfig(ctx context.Context, arg ListThoughtEdgesByConsultationAndRunConfigParams) ([]*ThoughtEdge, error)
	// Query pattern: fetch full pipeline artifacts for one consultation.
	ListThoughtsByConsultationAndRunConfig(ctx context.Context, arg ListThoughtsByConsultationAndRunConfigParams) ([]*Thought, error)
	ListTurnsByTranscript(ctx context.Context, transcriptID uuid.UUID) ([]*Turn, error)
	ListUsersByOrg(ctx context.Context, orgID uuid.UUID) ([]*User, error)
	MarkReferenceLabelVerified(ctx context.Context, arg MarkReferenceLabelVerifiedParams) (*ReferenceLabel, error)
	RevokeAllUserRefreshTokens(ctx context.Context, userID uuid.UUID) error
	RevokeConsentRecord(ctx context.Context, id uuid.UUID) (*ConsentRecord, error)
	RevokeRefreshToken(ctx context.Context, id uuid.UUID) error
	RevokeRefreshTokenFamily(ctx context.Context, familyID uuid.UUID) error
	RotateRefreshToken(ctx context.Context, arg RotateRefreshTokenParams) error
	// Written by the mandatory REDACT_RUNNING stage (§7.3); only this text is
	// ever placed in a prompt.
	SetTurnRedactedText(ctx context.Context, arg SetTurnRedactedTextParams) (*Turn, error)
	UpdateConsultationState(ctx context.Context, arg UpdateConsultationStateParams) (*Consultation, error)
	UpdateEvalRunStatus(ctx context.Context, arg UpdateEvalRunStatusParams) (*EvalRun, error)
	UpdateJobStageResult(ctx context.Context, arg UpdateJobStageResultParams) (*JobStage, error)
	UpdateJobState(ctx context.Context, arg UpdateJobStateParams) (*Job, error)
}

var _ Querier = (*Queries)(nil)
