// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: reference_labels.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createReferenceLabel = `-- name: CreateReferenceLabel :one
INSERT INTO reference_labels (consultation_id, field_key, value, provenance, generated_by_model)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, consultation_id, field_key, value, provenance, generated_by_model, verified_by_user, verified_at, created_at
`

type CreateReferenceLabelParams struct {
	ConsultationID   uuid.UUID   `db:"consultation_id" json:"consultation_id"`
	FieldKey         string      `db:"field_key" json:"field_key"`
	Value            []byte      `db:"value" json:"value"`
	Provenance       string      `db:"provenance" json:"provenance"`
	GeneratedByModel pgtype.Text `db:"generated_by_model" json:"generated_by_model"`
}

func (q *Queries) CreateReferenceLabel(ctx context.Context, arg CreateReferenceLabelParams) (*ReferenceLabel, error) {
	row := q.db.QueryRow(ctx, createReferenceLabel,
		arg.ConsultationID,
		arg.FieldKey,
		arg.Value,
		arg.Provenance,
		arg.GeneratedByModel,
	)
	var i ReferenceLabel
	err := row.Scan(
		&i.ID,
		&i.ConsultationID,
		&i.FieldKey,
		&i.Value,
		&i.Provenance,
		&i.GeneratedByModel,
		&i.VerifiedByUser,
		&i.VerifiedAt,
		&i.CreatedAt,
	)
	return &i, err
}

const listReferenceLabelsByConsultation = `-- name: ListReferenceLabelsByConsultation :many
SELECT id, consultation_id, field_key, value, provenance, generated_by_model, verified_by_user, verified_at, created_at FROM reference_labels WHERE consultation_id = $1 ORDER BY field_key
`

func (q *Queries) ListReferenceLabelsByConsultation(ctx context.Context, consultationID uuid.UUID) ([]*ReferenceLabel, error) {
	rows, err := q.db.Query(ctx, listReferenceLabelsByConsultation, consultationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*ReferenceLabel
	for rows.Next() {
		var i ReferenceLabel
		if err := rows.Scan(
			&i.ID,
			&i.ConsultationID,
			&i.FieldKey,
			&i.Value,
			&i.Provenance,
			&i.GeneratedByModel,
			&i.VerifiedByUser,
			&i.VerifiedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markReferenceLabelVerified = `-- name: MarkReferenceLabelVerified :one
UPDATE reference_labels
SET provenance = 'human_verified', verified_by_user = $2, verified_at = now()
WHERE id = $1
RETURNING id, consultation_id, field_key, value, provenance, generated_by_model, verified_by_user, verified_at, created_at
`

type MarkReferenceLabelVerifiedParams struct {
	ID             uuid.UUID   `db:"id" json:"id"`
	VerifiedByUser pgtype.UUID `db:"verified_by_user" json:"verified_by_user"`
}

func (q *Queries) MarkReferenceLabelVerified(ctx context.Context, arg MarkReferenceLabelVerifiedParams) (*ReferenceLabel, error) {
	row := q.db.QueryRow(ctx, markReferenceLabelVerified, arg.ID, arg.VerifiedByUser)
	var i ReferenceLabel
	err := row.Scan(
		&i.ID,
		&i.ConsultationID,
		&i.FieldKey,
		&i.Value,
		&i.Provenance,
		&i.GeneratedByModel,
		&i.VerifiedByUser,
		&i.VerifiedAt,
		&i.CreatedAt,
	)
	return &i, err
}
