// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: reviews.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const completeReview = `-- name: CompleteReview :one
UPDATE reviews SET completed_at = now(), outcome = $2 WHERE id = $1 RETURNING id, clinical_note_id, reviewer_user_id, started_at, completed_at, outcome, created_at, updated_at
`

type CompleteReviewParams struct {
	ID      uuid.UUID   `db:"id" json:"id"`
	Outcome pgtype.Text `db:"outcome" json:"outcome"`
}

func (q *Queries) CompleteReview(ctx context.Context, arg CompleteReviewParams) (*Review, error) {
	row := q.db.QueryRow(ctx, completeReview, arg.ID, arg.Outcome)
	var i Review
	err := row.Scan(
		&i.ID,
		&i.ClinicalNoteID,
		&i.ReviewerUserID,
		&i.StartedAt,
		&i.CompletedAt,
		&i.Outcome,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const createReview = `-- name: CreateReview :one
INSERT INTO reviews (clinical_note_id, reviewer_user_id)
VALUES ($1, $2)
RETURNING id, clinical_note_id, reviewer_user_id, started_at, completed_at, outcome, created_at, updated_at
`

type CreateReviewParams struct {
	ClinicalNoteID uuid.UUID `db:"clinical_note_id" json:"clinical_note_id"`
	ReviewerUserID uuid.UUID `db:"reviewer_user_id" json:"reviewer_user_id"`
}

func (q *Queries) CreateReview(ctx context.Context, arg CreateReviewParams) (*Review, error) {
	row := q.db.QueryRow(ctx, createReview, arg.ClinicalNoteID, arg.ReviewerUserID)
	var i Review
	err := row.Scan(
		&i.ID,
		&i.ClinicalNoteID,
		&i.ReviewerUserID,
		&i.StartedAt,
		&i.CompletedAt,
		&i.Outcome,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const getReview = `-- name: GetReview :one
SELECT id, clinical_note_id, reviewer_user_id, started_at, completed_at, outcome, created_at, updated_at FROM reviews WHERE id = $1
`

func (q *Queries) GetReview(ctx context.Context, id uuid.UUID) (*Review, error) {
	row := q.db.QueryRow(ctx, getReview, id)
	var i Review
	err := row.Scan(
		&i.ID,
		&i.ClinicalNoteID,
		&i.ReviewerUserID,
		&i.StartedAt,
		&i.CompletedAt,
		&i.Outcome,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}
