// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: review_edits.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const createReviewEdit = `-- name: CreateReviewEdit :one
INSERT INTO review_edits (review_id, field_key, original_value, edited_value, edit_type, editor_user_id)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, review_id, field_key, original_value, edited_value, edit_type, edited_at, editor_user_id
`

type CreateReviewEditParams struct {
	ReviewID      uuid.UUID `db:"review_id" json:"review_id"`
	FieldKey      string    `db:"field_key" json:"field_key"`
	OriginalValue []byte    `db:"original_value" json:"original_value"`
	EditedValue   []byte    `db:"edited_value" json:"edited_value"`
	EditType      string    `db:"edit_type" json:"edit_type"`
	EditorUserID  uuid.UUID `db:"editor_user_id" json:"editor_user_id"`
}

// The HITL data flywheel (decision #14).
func (q *Queries) CreateReviewEdit(ctx context.Context, arg CreateReviewEditParams) (*ReviewEdit, error) {
	row := q.db.QueryRow(ctx, createReviewEdit,
		arg.ReviewID,
		arg.FieldKey,
		arg.OriginalValue,
		arg.EditedValue,
		arg.EditType,
		arg.EditorUserID,
	)
	var i ReviewEdit
	err := row.Scan(
		&i.ID,
		&i.ReviewID,
		&i.FieldKey,
		&i.OriginalValue,
		&i.EditedValue,
		&i.EditType,
		&i.EditedAt,
		&i.EditorUserID,
	)
	return &i, err
}

const listReviewEditsByReview = `-- name: ListReviewEditsByReview :many
SELECT id, review_id, field_key, original_value, edited_value, edit_type, edited_at, editor_user_id FROM review_edits WHERE review_id = $1 ORDER BY edited_at
`

func (q *Queries) ListReviewEditsByReview(ctx context.Context, reviewID uuid.UUID) ([]*ReviewEdit, error) {
	rows, err := q.db.Query(ctx, listReviewEditsByReview, reviewID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*ReviewEdit
	for rows.Next() {
		var i ReviewEdit
		if err := rows.Scan(
			&i.ID,
			&i.ReviewID,
			&i.FieldKey,
			&i.OriginalValue,
			&i.EditedValue,
			&i.EditType,
			&i.EditedAt,
			&i.EditorUserID,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
