// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: run_configs.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const createRunConfig = `-- name: CreateRunConfig :one
INSERT INTO run_configs (content_hash, arm, config, schema_version)
VALUES ($1, $2, $3, $4)
ON CONFLICT (content_hash) DO UPDATE SET content_hash = EXCLUDED.content_hash
RETURNING id, content_hash, arm, config, schema_version, created_at
`

type CreateRunConfigParams struct {
	ContentHash   string `db:"content_hash" json:"content_hash"`
	Arm           string `db:"arm" json:"arm"`
	Config        []byte `db:"config" json:"config"`
	SchemaVersion int32  `db:"schema_version" json:"schema_version"`
}

// Configs are interned on content_hash (ADR-0012): a config that already
// exists returns the existing row instead of duplicating it.
func (q *Queries) CreateRunConfig(ctx context.Context, arg CreateRunConfigParams) (*RunConfig, error) {
	row := q.db.QueryRow(ctx, createRunConfig,
		arg.ContentHash,
		arg.Arm,
		arg.Config,
		arg.SchemaVersion,
	)
	var i RunConfig
	err := row.Scan(
		&i.ID,
		&i.ContentHash,
		&i.Arm,
		&i.Config,
		&i.SchemaVersion,
		&i.CreatedAt,
	)
	return &i, err
}

const getRunConfig = `-- name: GetRunConfig :one
SELECT id, content_hash, arm, config, schema_version, created_at FROM run_configs WHERE id = $1
`

func (q *Queries) GetRunConfig(ctx context.Context, id uuid.UUID) (*RunConfig, error) {
	row := q.db.QueryRow(ctx, getRunConfig, id)
	var i RunConfig
	err := row.Scan(
		&i.ID,
		&i.ContentHash,
		&i.Arm,
		&i.Config,
		&i.SchemaVersion,
		&i.CreatedAt,
	)
	return &i, err
}

const getRunConfigByContentHash = `-- name: GetRunConfigByContentHash :one
SELECT id, content_hash, arm, config, schema_version, created_at FROM run_configs WHERE content_hash = $1
`

func (q *Queries) GetRunConfigByContentHash(ctx context.Context, contentHash string) (*RunConfig, error) {
	row := q.db.QueryRow(ctx, getRunConfigByContentHash, contentHash)
	var i RunConfig
	err := row.Scan(
		&i.ID,
		&i.ContentHash,
		&i.Arm,
		&i.Config,
		&i.SchemaVersion,
		&i.CreatedAt,
	)
	return &i, err
}
