// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: summaries.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createSummary = `-- name: CreateSummary :one
INSERT INTO summaries (consultation_id, run_config_id, text, rouge_l, bertscore)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, consultation_id, run_config_id, text, rouge_l, bertscore, created_at
`

type CreateSummaryParams struct {
	ConsultationID uuid.UUID     `db:"consultation_id" json:"consultation_id"`
	RunConfigID    uuid.UUID     `db:"run_config_id" json:"run_config_id"`
	Text           string        `db:"text" json:"text"`
	RougeL         pgtype.Float8 `db:"rouge_l" json:"rouge_l"`
	Bertscore      pgtype.Float8 `db:"bertscore" json:"bertscore"`
}

func (q *Queries) CreateSummary(ctx context.Context, arg CreateSummaryParams) (*Summary, error) {
	row := q.db.QueryRow(ctx, createSummary,
		arg.ConsultationID,
		arg.RunConfigID,
		arg.Text,
		arg.RougeL,
		arg.Bertscore,
	)
	var i Summary
	err := row.Scan(
		&i.ID,
		&i.ConsultationID,
		&i.RunConfigID,
		&i.Text,
		&i.RougeL,
		&i.Bertscore,
		&i.CreatedAt,
	)
	return &i, err
}

const getSummaryForConsultationAndRunConfig = `-- name: GetSummaryForConsultationAndRunConfig :one
SELECT id, consultation_id, run_config_id, text, rouge_l, bertscore, created_at FROM summaries WHERE consultation_id = $1 AND run_config_id = $2
`

type GetSummaryForConsultationAndRunConfigParams struct {
	ConsultationID uuid.UUID `db:"consultation_id" json:"consultation_id"`
	RunConfigID    uuid.UUID `db:"run_config_id" json:"run_config_id"`
}

// Query pattern: fetch full pipeline artifacts for one consultation.
func (q *Queries) GetSummaryForConsultationAndRunConfig(ctx context.Context, arg GetSummaryForConsultationAndRunConfigParams) (*Summary, error) {
	row := q.db.QueryRow(ctx, getSummaryForConsultationAndRunConfig, arg.ConsultationID, arg.RunConfigID)
	var i Summary
	err := row.Scan(
		&i.ID,
		&i.ConsultationID,
		&i.RunConfigID,
		&i.Text,
		&i.RougeL,
		&i.Bertscore,
		&i.CreatedAt,
	)
	return &i, err
}
