// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: thoughts.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createThought = `-- name: CreateThought :one
INSERT INTO thoughts (consultation_id, run_config_id, turn_id, speaker, text, entities, category, temporal_anchor, linked_concepts)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, consultation_id, run_config_id, turn_id, speaker, text, entities, category, temporal_anchor, linked_concepts, created_at
`

type CreateThoughtParams struct {
	ConsultationID uuid.UUID   `db:"consultation_id" json:"consultation_id"`
	RunConfigID    uuid.UUID   `db:"run_config_id" json:"run_config_id"`
	TurnID         uuid.UUID   `db:"turn_id" json:"turn_id"`
	Speaker        string      `db:"speaker" json:"speaker"`
	Text           string      `db:"text" json:"text"`
	Entities       []byte      `db:"entities" json:"entities"`
	Category       string      `db:"category" json:"category"`
	TemporalAnchor pgtype.Text `db:"temporal_anchor" json:"temporal_anchor"`
	LinkedConcepts []byte      `db:"linked_concepts" json:"linked_concepts"`
}

func (q *Queries) CreateThought(ctx context.Context, arg CreateThoughtParams) (*Thought, error) {
	row := q.db.QueryRow(ctx, createThought,
		arg.ConsultationID,
		arg.RunConfigID,
		arg.TurnID,
		arg.Speaker,
		arg.Text,
		arg.Entities,
		arg.Category,
		arg.TemporalAnchor,
		arg.LinkedConcepts,
	)
	var i Thought
	err := row.Scan(
		&i.ID,
		&i.ConsultationID,
		&i.RunConfigID,
		&i.TurnID,
		&i.Speaker,
		&i.Text,
		&i.Entities,
		&i.Category,
		&i.TemporalAnchor,
		&i.LinkedConcepts,
		&i.CreatedAt,
	)
	return &i, err
}

const listThoughtsByConsultationAndRunConfig = `-- name: ListThoughtsByConsultationAndRunConfig :many
SELECT id, consultation_id, run_config_id, turn_id, speaker, text, entities, category, temporal_anchor, linked_concepts, created_at FROM thoughts WHERE consultation_id = $1 AND run_config_id = $2 ORDER BY created_at
`

type ListThoughtsByConsultationAndRunConfigParams struct {
	ConsultationID uuid.UUID `db:"consultation_id" json:"consultation_id"`
	RunConfigID    uuid.UUID `db:"run_config_id" json:"run_config_id"`
}

// Query pattern: fetch full pipeline artifacts for one consultation.
func (q *Queries) ListThoughtsByConsultationAndRunConfig(ctx context.Context, arg ListThoughtsByConsultationAndRunConfigParams) ([]*Thought, error) {
	rows, err := q.db.Query(ctx, listThoughtsByConsultationAndRunConfig, arg.ConsultationID, arg.RunConfigID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*Thought
	for rows.Next() {
		var i Thought
		if err := rows.Scan(
			&i.ID,
			&i.ConsultationID,
			&i.RunConfigID,
			&i.TurnID,
			&i.Speaker,
			&i.Text,
			&i.Entities,
			&i.Category,
			&i.TemporalAnchor,
			&i.LinkedConcepts,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
