// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: thought_edges.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const createThoughtEdge = `-- name: CreateThoughtEdge :one
INSERT INTO thought_edges (consultation_id, run_config_id, src_thought_id, dst_thought_id, edge_type, weight, predicted_by)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, consultation_id, run_config_id, src_thought_id, dst_thought_id, edge_type, weight, predicted_by, created_at
`

type CreateThoughtEdgeParams struct {
	ConsultationID uuid.UUID `db:"consultation_id" json:"consultation_id"`
	RunConfigID    uuid.UUID `db:"run_config_id" json:"run_config_id"`
	SrcThoughtID   uuid.UUID `db:"src_thought_id" json:"src_thought_id"`
	DstThoughtID   uuid.UUID `db:"dst_thought_id" json:"dst_thought_id"`
	EdgeType       string    `db:"edge_type" json:"edge_type"`
	Weight         float32   `db:"weight" json:"weight"`
	PredictedBy    string    `db:"predicted_by" json:"predicted_by"`
}

func (q *Queries) CreateThoughtEdge(ctx context.Context, arg CreateThoughtEdgeParams) (*ThoughtEdge, error) {
	row := q.db.QueryRow(ctx, createThoughtEdge,
		arg.ConsultationID,
		arg.RunConfigID,
		arg.SrcThoughtID,
		arg.DstThoughtID,
		arg.EdgeType,
		arg.Weight,
		arg.PredictedBy,
	)
	var i ThoughtEdge
	err := row.Scan(
		&i.ID,
		&i.ConsultationID,
		&i.RunConfigID,
		&i.SrcThoughtID,
		&i.DstThoughtID,
		&i.EdgeType,
		&i.Weight,
		&i.PredictedBy,
		&i.CreatedAt,
	)
	return &i, err
}

const listThoughtEdgesByConsultationAndRunConfig = `-- name: ListThoughtEdgesByConsultationAndRunConfig :many
SELECT id, consultation_id, run_config_id, src_thought_id, dst_thought_id, edge_type, weight, predicted_by, created_at FROM thought_edges WHERE consultation_id = $1 AND run_config_id = $2
`

type ListThoughtEdgesByConsultationAndRunConfigParams struct {
	ConsultationID uuid.UUID `db:"consultation_id" json:"consultation_id"`
	RunConfigID    uuid.UUID `db:"run_config_id" json:"run_config_id"`
}

// Query pattern: fetch full pipeline artifacts for one consultation — the
// serialized thought graph (nodes from ListThoughtsByConsultationAndRunConfig,
// edges from here) for the case-study figures (plan.md Phase 6/10).
func (q *Queries) ListThoughtEdgesByConsultationAndRunConfig(ctx context.Context, arg ListThoughtEdgesByConsultationAndRunConfigParams) ([]*ThoughtEdge, error) {
	rows, err := q.db.Query(ctx, listThoughtEdgesByConsultationAndRunConfig, arg.ConsultationID, arg.RunConfigID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*ThoughtEdge
	for rows.Next() {
		var i ThoughtEdge
		if err := rows.Scan(
			&i.ID,
			&i.ConsultationID,
			&i.RunConfigID,
			&i.SrcThoughtID,
			&i.DstThoughtID,
			&i.EdgeType,
			&i.Weight,
			&i.PredictedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
