// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: transcripts.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createTranscript = `-- name: CreateTranscript :one
INSERT INTO transcripts (consultation_id, run_config_id, uri, asr_backend, asr_model, wer, der, language)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, consultation_id, run_config_id, uri, asr_backend, asr_model, wer, der, language, created_at
`

type CreateTranscriptParams struct {
	ConsultationID uuid.UUID     `db:"consultation_id" json:"consultation_id"`
	RunConfigID    uuid.UUID     `db:"run_config_id" json:"run_config_id"`
	Uri            string        `db:"uri" json:"uri"`
	AsrBackend     string        `db:"asr_backend" json:"asr_backend"`
	AsrModel       string        `db:"asr_model" json:"asr_model"`
	Wer            pgtype.Float8 `db:"wer" json:"wer"`
	Der            pgtype.Float8 `db:"der" json:"der"`
	Language       string        `db:"language" json:"language"`
}

func (q *Queries) CreateTranscript(ctx context.Context, arg CreateTranscriptParams) (*Transcript, error) {
	row := q.db.QueryRow(ctx, createTranscript,
		arg.ConsultationID,
		arg.RunConfigID,
		arg.Uri,
		arg.AsrBackend,
		arg.AsrModel,
		arg.Wer,
		arg.Der,
		arg.Language,
	)
	var i Transcript
	err := row.Scan(
		&i.ID,
		&i.ConsultationID,
		&i.RunConfigID,
		&i.Uri,
		&i.AsrBackend,
		&i.AsrModel,
		&i.Wer,
		&i.Der,
		&i.Language,
		&i.CreatedAt,
	)
	return &i, err
}

const getTranscriptForConsultationAndRunConfig = `-- name: GetTranscriptForConsultationAndRunConfig :one
SELECT id, consultation_id, run_config_id, uri, asr_backend, asr_model, wer, der, language, created_at FROM transcripts WHERE consultation_id = $1 AND run_config_id = $2
`

type GetTranscriptForConsultationAndRunConfigParams struct {
	ConsultationID uuid.UUID `db:"consultation_id" json:"consultation_id"`
	RunConfigID    uuid.UUID `db:"run_config_id" json:"run_config_id"`
}

func (q *Queries) GetTranscriptForConsultationAndRunConfig(ctx context.Context, arg GetTranscriptForConsultationAndRunConfigParams) (*Transcript, error) {
	row := q.db.QueryRow(ctx, getTranscriptForConsultationAndRunConfig, arg.ConsultationID, arg.RunConfigID)
	var i Transcript
	err := row.Scan(
		&i.ID,
		&i.ConsultationID,
		&i.RunConfigID,
		&i.Uri,
		&i.AsrBackend,
		&i.AsrModel,
		&i.Wer,
		&i.Der,
		&i.Language,
		&i.CreatedAt,
	)
	return &i, err
}
