// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: turns.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createTurn = `-- name: CreateTurn :one
INSERT INTO turns (transcript_id, turn_index, speaker_label, start_ms, end_ms, text, confidence)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, transcript_id, turn_index, speaker_label, start_ms, end_ms, text, text_redacted, confidence, created_at
`

type CreateTurnParams struct {
	TranscriptID uuid.UUID     `db:"transcript_id" json:"transcript_id"`
	TurnIndex    int32         `db:"turn_index" json:"turn_index"`
	SpeakerLabel string        `db:"speaker_label" json:"speaker_label"`
	StartMs      int32         `db:"start_ms" json:"start_ms"`
	EndMs        int32         `db:"end_ms" json:"end_ms"`
	Text         string        `db:"text" json:"text"`
	Confidence   pgtype.Float4 `db:"confidence" json:"confidence"`
}

func (q *Queries) CreateTurn(ctx context.Context, arg CreateTurnParams) (*Turn, error) {
	row := q.db.QueryRow(ctx, createTurn,
		arg.TranscriptID,
		arg.TurnIndex,
		arg.SpeakerLabel,
		arg.StartMs,
		arg.EndMs,
		arg.Text,
		arg.Confidence,
	)
	var i Turn
	err := row.Scan(
		&i.ID,
		&i.TranscriptID,
		&i.TurnIndex,
		&i.SpeakerLabel,
		&i.StartMs,
		&i.EndMs,
		&i.Text,
		&i.TextRedacted,
		&i.Confidence,
		&i.CreatedAt,
	)
	return &i, err
}

const listTurnsByTranscript = `-- name: ListTurnsByTranscript :many
SELECT id, transcript_id, turn_index, speaker_label, start_ms, end_ms, text, text_redacted, confidence, created_at FROM turns WHERE transcript_id = $1 ORDER BY turn_index
`

func (q *Queries) ListTurnsByTranscript(ctx context.Context, transcriptID uuid.UUID) ([]*Turn, error) {
	rows, err := q.db.Query(ctx, listTurnsByTranscript, transcriptID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*Turn
	for rows.Next() {
		var i Turn
		if err := rows.Scan(
			&i.ID,
			&i.TranscriptID,
			&i.TurnIndex,
			&i.SpeakerLabel,
			&i.StartMs,
			&i.EndMs,
			&i.Text,
			&i.TextRedacted,
			&i.Confidence,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setTurnRedactedText = `-- name: SetTurnRedactedText :one
UPDATE turns SET text_redacted = $2 WHERE id = $1 RETURNING id, transcript_id, turn_index, speaker_label, start_ms, end_ms, text, text_redacted, confidence, created_at
`

type SetTurnRedactedTextParams struct {
	ID           uuid.UUID   `db:"id" json:"id"`
	TextRedacted pgtype.Text `db:"text_redacted" json:"text_redacted"`
}

// Written by the mandatory REDACT_RUNNING stage (§7.3); only this text is
// ever placed in a prompt.
func (q *Queries) SetTurnRedactedText(ctx context.Context, arg SetTurnRedactedTextParams) (*Turn, error) {
	row := q.db.QueryRow(ctx, setTurnRedactedText, arg.ID, arg.TextRedacted)
	var i Turn
	err := row.Scan(
		&i.ID,
		&i.TranscriptID,
		&i.TurnIndex,
		&i.SpeakerLabel,
		&i.StartMs,
		&i.EndMs,
		&i.Text,
		&i.TextRedacted,
		&i.Confidence,
		&i.CreatedAt,
	)
	return &i, err
}
