/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/auth/login': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Exchange email/password for an access + refresh token pair. */
    post: operations['login']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/auth/refresh': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Rotate a refresh token. Reuse of an already-rotated token revokes its whole family. */
    post: operations['refresh']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/auth/logout': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Revoke exactly the presented refresh token. Idempotent. */
    post: operations['logout']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/auth/register': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Create a user in the caller's own org. admin-only. */
    post: operations['register']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/users': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** List every user in the caller's own org. admin-only. */
    get: operations['listUsers']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/audit-log': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** List audit_log entries for the caller's own org. admin | auditor. */
    get: operations['listAuditLog']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/consultations': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** List/filter/paginate consultations, org-scoped. admin | doctor | reviewer. */
    get: operations['listConsultations']
    put?: never
    /** Create a consultation with its owning consent record. admin | doctor. */
    post: operations['createConsultation']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/consultations/{id}': {
    parameters: {
      query?: never
      header?: never
      path: {
        id: components['parameters']['ConsultationId']
      }
      cookie?: never
    }
    /** Fetch one consultation by ID, org-scoped. admin | doctor | reviewer. */
    get: operations['getConsultation']
    put?: never
    post?: never
    /** Cascading deletion (DPDP erasure requirement): every artifact object in MinIO for this consultation, then the consultations row and everything that cascades from it (jobs, transcripts, thoughts, clinical_notes, reviews, ...). consent_records is retained. Audit- logged with a before-snapshot, since the row is gone afterward. admin | doctor. */
    delete: operations['deleteConsultation']
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/consultations/{id}/audio/presign': {
    parameters: {
      query?: never
      header?: never
      path: {
        id: components['parameters']['ConsultationId']
      }
      cookie?: never
    }
    get?: never
    put?: never
    /** Get a time-limited MinIO PUT URL. Audio bytes go directly from the caller to object storage — go-api never touches them (docs/architecture.md §1.2). admin | doctor. */
    post: operations['presignConsultationAudio']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/consultations/{id}/audio/confirm': {
    parameters: {
      query?: never
      header?: never
      path: {
        id: components['parameters']['ConsultationId']
      }
      cookie?: never
    }
    get?: never
    put?: never
    /** Verify the presigned upload landed (MinIO StatObject) and record it as the consultation's source audio (uploaded -> pipeline_state). admin | doctor. */
    post: operations['confirmConsultationAudio']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/consultations/{id}/jobs': {
    parameters: {
      query?: never
      header?: never
      path: {
        id: components['parameters']['ConsultationId']
      }
      cookie?: never
    }
    get?: never
    put?: never
    /** Enqueue one pipeline run. Never blocks on processing — returns 202 once the job row is durably created. go-orchestrator picks it up either from the job.submitted signal or from its own dispatch scan, so the 202 holds whether or not Redis is reachable. admin | doctor. */
    post: operations['createJob']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/consultations/{id}/cancel': {
    parameters: {
      query?: never
      header?: never
      path: {
        id: components['parameters']['ConsultationId']
      }
      cookie?: never
    }
    get?: never
    put?: never
    /** Request cooperative cancellation (architecture.md §4.4). Sets consultations.cancel_requested and audit-logs it; it does not itself transition any state — go-orchestrator observes the flag, stops dispatching, and moves every non-terminal job of this consultation to `cancelled`, while the Python workers abort at their next checkpoint. In-flight provider calls are not interrupted, so tokens already spent stay accounted, and artifacts from completed stages are retained as valid inputs for a later re-run. Cancelling all of a consultation's ablation arms, since the flag is consultation-scoped. Idempotent. admin | doctor. */
    post: operations['cancelConsultation']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/consultations/{id}/result': {
    parameters: {
      query?: never
      header?: never
      path: {
        id: components['parameters']['ConsultationId']
      }
      cookie?: never
    }
    /** Assembled transcript, clinical note, summary, and artifact links for the consultation's most recent job. admin | doctor | reviewer. */
    get: operations['getConsultationResult']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/consultations/{id}/transcript': {
    parameters: {
      query?: never
      header?: never
      path: {
        id: components['parameters']['ConsultationId']
      }
      cookie?: never
    }
    /** Time-limited MinIO GET URL for the transcript artifact — the download-side mirror of the audio upload presign endpoint. go-api never reads the artifact bytes itself (docs/architecture.md §1.2); the caller fetches `download_url` directly from MinIO and parses the protojson-encoded `Transcript` message (proto/coda/v1/ transcript.proto: `turns[]`, each `{ turn_index, speaker_label, start_ms, end_ms, text, text_redacted, confidence, words[] }`). admin | doctor | reviewer. */
    get: operations['presignConsultationTranscript']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/jobs/{id}': {
    parameters: {
      query?: never
      header?: never
      path: {
        id: components['parameters']['JobId']
      }
      cookie?: never
    }
    /** Job status with per-stage state, a rough progress percentage, timings, and error detail. admin | doctor | reviewer. */
    get: operations['getJob']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/jobs/{id}/events': {
    parameters: {
      query?: never
      header?: never
      path: {
        id: components['parameters']['JobId']
      }
      cookie?: never
    }
    /** Server-Sent Events stream of stage transitions and progress heartbeats. Polls job/job_stages on a 2s interval and emits an `event: stage` frame on change (plus a `: heartbeat` comment every 15s), until the job reaches a terminal state, the client disconnects, or 30 minutes elapse. */
    get: operations['jobEvents']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
}
export type webhooks = Record<string, never>
export interface components {
  schemas: {
    Error: {
      error: string
    }
    LoginRequest: {
      /** Format: email */
      email: string
      password: string
    }
    RefreshRequest: {
      refresh_token: string
    }
    TokenResponse: {
      access_token?: string
      refresh_token?: string
      /** @example Bearer */
      token_type?: string
      /** @description Seconds until access_token expires. */
      expires_in?: number
    }
    RegisterRequest: {
      /** Format: email */
      email: string
      password: string
      /** @enum {string} */
      role: 'admin' | 'doctor' | 'reviewer' | 'auditor'
    }
    User: {
      /** Format: uuid */
      id?: string
      /** Format: uuid */
      org_id?: string
      email?: string
      /** @enum {string} */
      role?: 'admin' | 'doctor' | 'reviewer' | 'auditor'
      active?: boolean
    }
    AuditLogEntry: {
      /** Format: uuid */
      id?: string
      /** Format: uuid */
      org_id?: string
      /** Format: uuid */
      actor_user_id?: string | null
      actor_service?: string
      action?: string
      resource_type?: string
      resource_id?: string
      /** @enum {string} */
      outcome?: 'success' | 'failure'
    }
    Consultation: {
      /** Format: uuid */
      id?: string
      /** Format: uuid */
      org_id?: string
      /** @description One pipeline_state value (docs/architecture.md §4.1). */
      state?: string
      /** @description Always "en" in v1 (claude_context.md §2.1) — "kn_en" is a v2 value already legal on the wire/schema. */
      language?: string
    }
    CreateConsultationRequest: {
      /**
       * @description Only "en" is accepted in v1; anything else is rejected with 422, never silently relabeled.
       * @default en
       */
      language: string
      consent: {
        /** @description Must be true — an omitted or false value is rejected with 422. */
        consent_obtained: boolean
        /** @example verbal */
        consent_type: string
        consent_method?: string
        /** @description Pseudonymous reference, never a name (docs/architecture.md §5.1). Server-generated if omitted. */
        subject_ref?: string
      }
    }
    AudioPresignRequest: {
      /** @enum {string} */
      content_type: 'audio/wav' | 'audio/x-wav' | 'audio/wave' | 'audio/mpeg' | 'audio/mp3'
      /** Format: int64 */
      size_bytes: number
      sha256: string
    }
    AudioPresignResponse: {
      /** Format: uri */
      upload_url?: string
      object_key?: string
      /** @example PUT */
      method?: string
      /** Format: date-time */
      expires_at?: string
    }
    AudioConfirmRequest: {
      object_key: string
      sha256: string
      /** Format: double */
      duration_sec: number
    }
    CreateJobRequest: {
      /**
       * @description Ablation arm (docs/architecture.md §6.2). Defaults to "baseline" when omitted.
       * @default baseline
       * @enum {string}
       */
      arm: 'baseline' | 'got_k1' | 'got_k2' | 'got_k2_nograph' | 'got_k2_kg' | 'frontier_ref'
    }
    Job: {
      /** Format: uuid */
      id?: string
      /** Format: uuid */
      consultation_id?: string
      /** Format: uuid */
      run_config_id?: string
      arm?: string
      state?: string
      /** @enum {string} */
      current_stage?: 'asr' | 'redact' | 'nlp' | 'export'
      attempt?: number
      /** Format: date-time */
      resume_after?: string | null
      error?: Record<string, never> | null
      /** @description succeeded-stage-count / 4 * 100 — a rough measure, not a weighted estimate. */
      progress_percent?: number
      stages?: components['schemas']['JobStage'][]
    }
    CancelConsultation: {
      /** Format: uuid */
      consultation_id?: string
      cancel_requested?: boolean
      /** @description The consultation's state at the moment the flag was set. It is not yet `cancelled` — go-orchestrator owns that transition (ADR-0006) and applies it on its next cancellation sweep. */
      state?: string
    }
    JobStage: {
      /** @enum {string} */
      stage?: 'asr' | 'redact' | 'nlp' | 'export'
      /** @enum {string} */
      status?: 'pending' | 'running' | 'succeeded' | 'failed' | 'quota_exhausted' | 'cancelled'
      attempt?: number
      /** Format: date-time */
      started_at?: string | null
      /** Format: date-time */
      finished_at?: string | null
      result_ref?: string
      /** @description tokens_in/tokens_out/llm_calls/cache_hits/wall_ms (docs/architecture.md §2.2 StageMetrics). */
      metrics?: Record<string, never>
      /**
       * Format: float
       * @description Worker-reported progress within this stage, from the StageHeartbeat go-orchestrator lands on job_stages every 15s (§2.4). Forced to 100 once the stage succeeds.
       */
      percent_complete?: number
      /** @description Free-text label from the latest heartbeat, e.g. "diarizing". */
      step?: string
      /**
       * Format: date-time
       * @description When the latest heartbeat arrived. Null before the first one.
       */
      heartbeat_at?: string | null
    }
    TranscriptPresignResponse: {
      /** Format: uri */
      download_url?: string
      /** Format: date-time */
      expires_at?: string
    }
    Word: {
      text?: string
      start_ms?: number
      end_ms?: number
      /** Format: float */
      confidence?: number
      speaker_cluster_id?: string
    }
    /** @description One speaker-labeled, timestamped utterance (proto/coda/v1/transcript.proto). Fetched via the presigned URL from `GET /consultations/{id}/transcript`, never inline in any go-api response. */
    Turn: {
      turn_index?: number
      /** @enum {string} */
      speaker_label?:
        | 'SPEAKER_ROLE_UNSPECIFIED'
        | 'SPEAKER_ROLE_DOCTOR'
        | 'SPEAKER_ROLE_PATIENT'
        | 'SPEAKER_ROLE_UNKNOWN'
      start_ms?: number
      end_ms?: number
      /** @description Original text. Only text_redacted ever reached an LLM prompt (ADR-0014) */
      text?: string
      text_redacted?: string
      /** Format: float */
      confidence?: number
      words?: components['schemas']['Word'][]
    }
    /** @description The shape of the JSON blob at TranscriptPresignResponse.download_url — not returned by any go-api endpoint directly. */
    TranscriptArtifact: {
      consultation_id?: string
      run_config_id?: string
      language?: string
      asr_backend?: string
      asr_model?: string
      turns?: components['schemas']['Turn'][]
      wer?: number | null
      der?: number | null
    }
    /** @description One extracted field's value with provenance (claude_context.md §3). A field with nothing stated is omitted entirely by protojson, not present as null — treat a missing key the same as "not stated". */
    FieldValue: {
      value?: string
      source_turn_ids?: number[]
      /** Format: float */
      confidence?: number
      linked_concepts?: string[]
    }
    /** @description The 8-field JSON note (proto/coda/v1/clinical.proto), protojson- encoded with preserving_proto_field_name — the exact shape of ConsultationResult.clinical_note. Any field/list may be entirely absent (not stated), never fabricated. */
    ClinicalNote: {
      consultation_id?: string
      run_config_id?: string
      version?: number
      /** @enum {string} */
      status?:
        | 'NOTE_STATUS_UNSPECIFIED'
        | 'NOTE_STATUS_DRAFT'
        | 'NOTE_STATUS_UNDER_REVIEW'
        | 'NOTE_STATUS_APPROVED'
      chief_complaint?: components['schemas']['FieldValue']
      hopi?: components['schemas']['FieldValue']
      past_medical_history?: components['schemas']['FieldValue'][]
      medications_allergies?: {
        medications?: components['schemas']['FieldValue'][]
        allergies?: components['schemas']['FieldValue'][]
      }
      examination_findings?: components['schemas']['FieldValue']
      provisional_diagnosis?: components['schemas']['FieldValue'][]
      investigations_advised?: components['schemas']['FieldValue'][]
      treatment_plan?: components['schemas']['FieldValue']
      approved_by?: string
      approved_at?: string
    }
    ConsultationResult: {
      /** Format: uuid */
      consultation_id?: string
      /** Format: uuid */
      job_id?: string
      /** Format: uuid */
      run_config_id?: string
      state?: string
      transcript?: {
        uri?: string
        asr_backend?: string
        asr_model?: string
        language?: string
        wer?: number
        der?: number
      } | null
      summary?: {
        text?: string
      } | null
      clinical_note?: components['schemas']['ClinicalNote'] | null
      artifacts?: {
        kind?: string
        uri?: string
      }[]
    }
  }
  responses: {
    /** @description Malformed request body. */
    BadRequest: {
      headers: {
        [name: string]: unknown
      }
      content: {
        'application/json': components['schemas']['Error']
      }
    }
    /** @description Missing or invalid bearer token. */
    Unauthorized: {
      headers: {
        [name: string]: unknown
      }
      content: {
        'application/json': components['schemas']['Error']
      }
    }
    /** @description Authenticated, but the caller's role does not permit this action. */
    Forbidden: {
      headers: {
        [name: string]: unknown
      }
      content: {
        'application/json': components['schemas']['Error']
      }
    }
    /** @description Not found — including a resource that exists but belongs to a different org (docs/architecture.md §7.6: cross-org existence must never leak as 403). */
    NotFound: {
      headers: {
        [name: string]: unknown
      }
      content: {
        'application/json': components['schemas']['Error']
      }
    }
  }
  parameters: {
    ConsultationId: string
    JobId: string
    Limit: number
    Offset: number
  }
  requestBodies: never
  headers: never
  pathItems: never
}
export type $defs = Record<string, never>
export interface operations {
  login: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['LoginRequest']
      }
    }
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['TokenResponse']
        }
      }
      400: components['responses']['BadRequest']
      401: components['responses']['Unauthorized']
    }
  }
  refresh: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['RefreshRequest']
      }
    }
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['TokenResponse']
        }
      }
      400: components['responses']['BadRequest']
      401: components['responses']['Unauthorized']
    }
  }
  logout: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['RefreshRequest']
      }
    }
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      400: components['responses']['BadRequest']
    }
  }
  register: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['RegisterRequest']
      }
    }
    responses: {
      /** @description Created */
      201: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['User']
        }
      }
      400: components['responses']['BadRequest']
      401: components['responses']['Unauthorized']
      403: components['responses']['Forbidden']
      /** @description Email already registered */
      409: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  listUsers: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['User'][]
        }
      }
      401: components['responses']['Unauthorized']
      403: components['responses']['Forbidden']
    }
  }
  listAuditLog: {
    parameters: {
      query?: {
        limit?: components['parameters']['Limit']
        offset?: components['parameters']['Offset']
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['AuditLogEntry'][]
        }
      }
      401: components['responses']['Unauthorized']
      403: components['responses']['Forbidden']
    }
  }
  listConsultations: {
    parameters: {
      query?: {
        limit?: components['parameters']['Limit']
        offset?: components['parameters']['Offset']
        /** @description Filter to one pipeline_state value (docs/architecture.md §4.1). Omit for every state. */
        state?: string
        /** @description Filter to one language value. v1 data is always "en" (claude_context.md §2.1). */
        language?: string
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Consultation'][]
        }
      }
      401: components['responses']['Unauthorized']
      403: components['responses']['Forbidden']
    }
  }
  createConsultation: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['CreateConsultationRequest']
      }
    }
    responses: {
      /** @description Created */
      201: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Consultation']
        }
      }
      400: components['responses']['BadRequest']
      401: components['responses']['Unauthorized']
      403: components['responses']['Forbidden']
      /** @description consent.consent_obtained was not true, consent.consent_type was missing, or language was anything other than "en" (v1 is English-only — see claude_context.md §2.1; never silently relabeled). */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Error']
        }
      }
    }
  }
  getConsultation: {
    parameters: {
      query?: never
      header?: never
      path: {
        id: components['parameters']['ConsultationId']
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Consultation']
        }
      }
      401: components['responses']['Unauthorized']
      403: components['responses']['Forbidden']
      404: components['responses']['NotFound']
    }
  }
  deleteConsultation: {
    parameters: {
      query?: never
      header?: never
      path: {
        id: components['parameters']['ConsultationId']
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': {
            deleted?: boolean
            /** Format: uuid */
            id?: string
          }
        }
      }
      401: components['responses']['Unauthorized']
      403: components['responses']['Forbidden']
      404: components['responses']['NotFound']
    }
  }
  presignConsultationAudio: {
    parameters: {
      query?: never
      header?: never
      path: {
        id: components['parameters']['ConsultationId']
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['AudioPresignRequest']
      }
    }
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['AudioPresignResponse']
        }
      }
      400: components['responses']['BadRequest']
      401: components['responses']['Unauthorized']
      403: components['responses']['Forbidden']
      404: components['responses']['NotFound']
      /** @description Unsupported content_type, size_bytes out of range, or a malformed sha256, or the consultation was erased. */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Error']
        }
      }
      /** @description Object storage is not configured on this deployment. */
      503: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  confirmConsultationAudio: {
    parameters: {
      query?: never
      header?: never
      path: {
        id: components['parameters']['ConsultationId']
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['AudioConfirmRequest']
      }
    }
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Consultation']
        }
      }
      400: components['responses']['BadRequest']
      401: components['responses']['Unauthorized']
      403: components['responses']['Forbidden']
      404: components['responses']['NotFound']
      /** @description The object has not been uploaded to MinIO yet — the presigned PUT has not completed. */
      409: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Error']
        }
      }
      /** @description Malformed sha256/duration_sec, or object_key does not belong to this consultation. */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Error']
        }
      }
    }
  }
  createJob: {
    parameters: {
      query?: never
      header?: never
      path: {
        id: components['parameters']['ConsultationId']
      }
      cookie?: never
    }
    requestBody?: {
      content: {
        'application/json': components['schemas']['CreateJobRequest']
      }
    }
    responses: {
      /** @description Accepted */
      202: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Job']
        }
      }
      401: components['responses']['Unauthorized']
      403: components['responses']['Forbidden']
      404: components['responses']['NotFound']
      /** @description Audio has not been uploaded yet, the consultation was erased, or arm is not one of the known ablation arms. */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Error']
        }
      }
    }
  }
  cancelConsultation: {
    parameters: {
      query?: never
      header?: never
      path: {
        id: components['parameters']['ConsultationId']
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Cancellation requested */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['CancelConsultation']
        }
      }
      401: components['responses']['Unauthorized']
      403: components['responses']['Forbidden']
      404: components['responses']['NotFound']
    }
  }
  getConsultationResult: {
    parameters: {
      query?: never
      header?: never
      path: {
        id: components['parameters']['ConsultationId']
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ConsultationResult']
        }
      }
      401: components['responses']['Unauthorized']
      403: components['responses']['Forbidden']
      404: components['responses']['NotFound']
      /** @description Still processing — no job exists yet, the job hasn't reached awaiting_review, or the note hasn't been persisted yet. */
      409: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Error']
        }
      }
    }
  }
  presignConsultationTranscript: {
    parameters: {
      query?: never
      header?: never
      path: {
        id: components['parameters']['ConsultationId']
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['TranscriptPresignResponse']
        }
      }
      401: components['responses']['Unauthorized']
      403: components['responses']['Forbidden']
      404: components['responses']['NotFound']
      /** @description Still processing — no job exists yet, the job hasn't reached awaiting_review, or no transcript has been persisted yet. */
      409: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Error']
        }
      }
      /** @description Object storage is not configured on this deployment. */
      503: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  getJob: {
    parameters: {
      query?: never
      header?: never
      path: {
        id: components['parameters']['JobId']
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Job']
        }
      }
      401: components['responses']['Unauthorized']
      403: components['responses']['Forbidden']
      404: components['responses']['NotFound']
    }
  }
  jobEvents: {
    parameters: {
      query?: never
      header?: never
      path: {
        id: components['parameters']['JobId']
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description text/event-stream */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'text/event-stream': string
        }
      }
      401: components['responses']['Unauthorized']
      403: components['responses']['Forbidden']
      404: components['responses']['NotFound']
    }
  }
}
